TSK_USED_NEWYEAR_GIFT_DAILY		= 11 --su dung hop qua trong ngay
MAX_USED_NEWYEAR_GIFT_DAILY		= 10 
TSK_GET_NEWYEAR_GIFT_DAILY		= 12 --khong su dung
MAX_GET_NEWYEAR_GIFT_DAILY		= 10
TSK_USED_NEWYEAR_FIREWORKS		= 13 --su dung phao hoa trong ngay
MAX_USED_NEWYEAR_FIREWORKS		= 200
HetHanEventTetNguyenDan = 20180305

TSK_SUDUNG_BANHCHUNG		= 14
MAX_SUDUNG_BANHCHUNG		= 500

TSK_SUDUNG_MAMNGUQUA		= 15
MAX_SUDUNG_MAMNGUQUA		= 1000

TSK_BAOLIXI		= 16	--nhan bao li xi
TSK_BAOLIXISD = 17-- su dung bao li xi

nbaolixiBD = 20170127
nbaolixiKT = 20180305
DangCapYeuCau = 50