FROM centos:7

COPY ./zoneinfo/ /usr/share/zoneinfo/

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN yum -y update
RUN yum -y install libuuid.i686 libcrypto.so.6 libcurl.so.4

WORKDIR /src/jxser/server1/

CMD ["./jx_linux_y"]

## su dung cho anti cua PA GUARD
# CMD ./jx_linux_y.sh