Include("\\script\\event\\springfestival08\\allbrother\\head.lua")
Include("\\script\\event\\springfestival08\\allbrother\\itemlist.lua")
--------------------------------------------------------------------------
allbrother_0801_tbTaskList = {	
	[1] = {nTaskType = 1, szShow ="Vµo ThÇn Tiªn §éng T×m Cao l·o nh©n [ Thµnh §«  Thanh Thµnh S¬n  ThÇn Tiªn §éng [ Täa §é 234/204]."},
	[2] = {nTaskType = 1, szShow = "§Õn Tr­êng Giang Nguyªn §Çu T×m Giíi V« Tµ [ Thµnh §«  Tr­êng Giang Nguyªn §Çu [Täa §é 282/371]."},
	[3] = {nTaskType = 1, szShow = "§Õn L©m An T×m Tr­¬ng t­íng qu©n [Täa §é 185/213]."},
	[4] = {nTaskType = 1, szShow = "§Õn Ngò §éc Gi¸o thØnh gi¸o anh chµng mÆt ®en[ Tæng Tr¹i  GÆp H¾c DiÖn Lang Qu©n]."},
	[5] = {nTaskType = 1, szShow = "D¹o ch¬i B¸ch Hoa §×nh T×m Ng­êi ¦ng ý [ Thóy Yªn M«n  Hµ Mé TuyÕt]."},
	[6] = {nTaskType = 1, szShow = "Th­îng C«n Lu©n ph¸i t×m Ng­êi Hä KhÈu Anh  [ C«n L«n Ph¶i  KhÈu Anh [Täa §é 195/192]."},
	[7] = {nTaskType = 1, szShow = "§Õn Thanh Thµnh S¬n t×m chµng hä C¶nh Tö Kú [ Thµnh §«  Thanh Thµnh S¬n [Täa §é 230/245]."},
	[8] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n T×m tr¸ng sÜ 1 [ Täa §é 453/358..471/354..474/343..479/339] ."},
	[9] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n T×m tr¸ng sÜ 2 [ Täa §é 453/358..471/354..474/343..479/339] ."},
	[10] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n T×m tr¸ng sÜ 3 [ Täa §é 474/343 ] ."},
	[11] = {nTaskType = 1, szShow = "D¹o ch¬i rõng tróc §­êng M«n T×m Tr¸ng SÜ 4 [ Täa §é 453/358..471/354..474/343..479/339] ."},
	[12] = {nTaskType = 1, szShow = "§¨ng Vâ §ang S¬n T×m Chµng Hä DiÖp [ Täa §é 213/190]."},
	[13] = {nTaskType = 1, szShow = "Vµo Kª Qu¸n ®éng Hái Th¨m Nµng NhuËn N­¬ng Êy [ T­¬ng D­¬ng => Phôc Ng­u S¬n => Kª Qu¸n §éng [ Täa §é 202/184]."},
	[14] = {nTaskType = 1, szShow = "Qua §¹i Lý t×m Chµng T­¬ng T­ - §oµn T­ Thµnh [ Täa §é 191/197 ]."},
	[15] = {nTaskType = 0, szShow = "Thu thËp Long Tiªn H­¬ng Nang HÖ Méc [N.B CÊp 10], L­u Tiªn QuÇn HÖ Kim [¸o CÊp 10].", tbList = {allbrother_0801_tbItemList[1], allbrother_0801_tbItemList[16]			}},
	[16] = {nTaskType = 0, szShow = "Thu thËp Toµn Th¹ch Giíi ChØ hÖ Thñy [ NhÉn CÊp 10 ] , Tr©n Ch©u H¹ng Liªn hÖ méc [ Kh¸c ] .", tbList = {allbrother_0801_tbItemList[2],	allbrother_0801_tbItemList[17]			}},
	[17] = {nTaskType = 0, szShow = "Thu thËp Gi¸c H¶i Bæng hÖ Kim [ Bæng C©p 9] , Thiªn T»m Ngoa hÖ Thæ [Giµy CÊp 10] .", tbList = {allbrother_0801_tbItemList[3],	allbrother_0801_tbItemList[18]				}},
	[18] = {nTaskType = 0, szShow = "Thu thËp TuyÒn Long bµo hÖ Háa [ ¸o CÊp 10] , Du¬ng ChØ B¹ch Ngäc hÖ Thñy [ Ngäc Béi CÊp 10] .", tbList = {allbrother_0801_tbItemList[4],	allbrother_0801_tbItemList[19]			}},
	[19] = {nTaskType = 0, szShow = "T×m ngùa Tóc S­¬ng [B¸n Ngùa PT] , Phi Phông Ngoa hÖ Háa [Giµy CÊp 10]  .", tbList = {allbrother_0801_tbItemList[5], 	allbrother_0801_tbItemList[20]						}},
	[20] = {nTaskType = 0, szShow = "Thu thËp Toµn NghÖ Gi¸p hÖ Thñy [ Kh¸c ] , HuyÒn ThiÕt KiÕm hÖ Thñy [VK CÊp 10 ] .", tbList = {allbrother_0801_tbItemList[6],	allbrother_0801_tbItemList[21]				}},
	[21] = {nTaskType = 0, szShow = "Thu thËp Long L©n Yªu §¸i hÖ Kim [Kh¸c ] , ThiÕt Trñy thñ hÖ Thæ [Thî RÌn 3 Lang HuyÖn] ", tbList = {allbrother_0801_tbItemList[7],	allbrother_0801_tbItemList[22]			}},
	[22] = {nTaskType = 0, szShow = "Thu thËp Yªu §ao hÖ Háa [ Thî RÌn 3 Lang HuyÖn ] , Ng­ L¹p hÖ Kim [T¹p Hãa 3 Lang HuyÖn] .", tbList = {allbrother_0801_tbItemList[8],	allbrother_0801_tbItemList[23]					}},
	[23] = {nTaskType = 0, szShow = "Thu thËp Phông VÜ QuÇn [¸o CÊp 7]  - hÖ háa  , Tö phØ thóy hé th©n phï - hÖ kim [ Kh¸c] ", tbList = {allbrother_0801_tbItemList[9],	allbrother_0801_tbItemList[24]			}},
	[24] = {nTaskType = 0, szShow = "Thu thËp Háa NhuÖ Thu¬ng hÖ Méc [Kh¸c]  , Kim Phông TriÓn SÜ hÖ Méc [Nãn CÊp 10] .", tbList = {allbrother_0801_tbItemList[10],	allbrother_0801_tbItemList[25]			}},
	[25] = {nTaskType = 0, szShow = "Thu thËp Thanh §ång N÷ gi¸p hÖ Méc [ ¸o CÊp 2] , Ph¸ Thiªn KÝch hÖ Kim [VK CÊp 10].", tbList = {allbrother_0801_tbItemList[11],	allbrother_0801_tbItemList[26]			}},
	[26] = {nTaskType = 0, szShow = "Thu thËp ThÊt B¶o cµ sa hÖ Thñy [¸o CÊp 10] , B¨ng Ph¸ch Hµn Ngäc Tr¹c hÖ Háa [Kh¸c].", tbList = {allbrother_0801_tbItemList[12],	allbrother_0801_tbItemList[27]		}},
	[27] = {nTaskType = 0, szShow = "Thu thËp Kim Yªu §¸i hÖ Thæ [ §ai L­ng CÊp 8], Phi Phông Ngoa hÖ Thæ [Giµy CÊp 10] .", tbList = {allbrother_0801_tbItemList[13],	allbrother_0801_tbItemList[28]		}},
	[28] = {nTaskType = 0, szShow = "Thu thËp Tr©n Ch©u H¹ng Liªn hÖ Ho¶ [ Gi©y ChuyÒn CÊp 9], B¹ch PhØ Thóy Hé Th©n Phï hÖ Méc [Kh¸c] .", tbList = {allbrother_0801_tbItemList[14],	allbrother_0801_tbItemList[29]	}},
	[29] = {nTaskType = 0, szShow = "Thu thËp H¶i Lam B¶o Th¹ch Giíi ChØ hÖ Kim [Kh¸c], Ngùa §¹i UyÓn B¹ch M· [ B¸n Ngùa Ph­îng T­êng].", tbList = {allbrother_0801_tbItemList[15],	allbrother_0801_tbItemList[30]			}},
	[30] = {nTaskType = 0, szShow = "Thu thËp Thiªn NhÉn MËt Trang hÖ Háa [¸o CÊp 10] ", tbList = {allbrother_0801_tbItemList[31]}},
	[31] = {nTaskType = 0, szShow = "Thu thËp ngùa Tóc S­¬ng [ B¸n Ngùa BiÖn Kinh]", tbList = {allbrother_0801_tbItemList[5]}},
	[32] = {nTaskType = 0, szShow = "Thu thËp Kim Lò hµi hÖ Kim [ Giµy CÊp 10]", tbList = {allbrother_0801_tbItemList[32]}},
	[33] = {nTaskType = 0, szShow = "Thu thËp §¹i Phong §ao hÖ Méc [ Vò KhÝ CÊp 10]", tbList = {allbrother_0801_tbItemList[33]}},
	[34] = {nTaskType = 0, szShow = "Thu thËp HuyÒn ThiÕt KiÕm hÖ Thæ [ Vò KhÝ CÊp 10]", tbList = {allbrother_0801_tbItemList[34]}},
	[35] = {nTaskType = 0, szShow = "Thu thËp Cöu TiÕt Xu¬ng VÜ Ngoa hÖ Thñy [ Giµy CÊp 10]", tbList = {allbrother_0801_tbItemList[35]}},
	[36] = {nTaskType = 0, szShow = "Thu thËp Thiªn T»m Hé UyÓn hÖ Thæ [ Bao Tay CÊp 10]", tbList = {allbrother_0801_tbItemList[36]}},
	[37] = {nTaskType = 0, szShow = "Thu thËp Thiªn T»m Yªu §¸i hÖ Thæ [ §ai L­ng CÊp 10]", tbList = {allbrother_0801_tbItemList[37]}},
	[38] = {nTaskType = 0, szShow = "Thu thËp TrÇm Hu¬ng sam hÖ Háa [ Ngäc Béi CÊp 7]", tbList = {allbrother_0801_tbItemList[38]}},
	[39] = {nTaskType = 0, szShow = "Thu thËp TuyÒn Long bµo hÖ Méc [ ¸o CÊp 10] ", tbList = {allbrother_0801_tbItemList[39]}},
	[40] = {nTaskType = 0, szShow = "Thu thËp ¤ TÇm M·o hÖ Méc [ Nãn CÊp 10]", tbList = {allbrother_0801_tbItemList[40]}},
	[41] = {nTaskType = 0, szShow = "Thu thËp Khæng Tuíc Linh hÖ Méc [Vu KhÝ Xa CÊp 10]", tbList = {allbrother_0801_tbItemList[41]}},
	[42] = {nTaskType = 0, szShow = "Thu thËp Long Phông HuyÕt Ngäc Tr¹c hÖ Thæ [ Bao Tay CÊp 10]", tbList = {allbrother_0801_tbItemList[42]}},
	[43] = {nTaskType = 0, szShow = "Thu thËp Toµn Th¹ch Giíi ChØ hÖ Kim [ NhÉn CÊp 10]", tbList = {allbrother_0801_tbItemList[43]}},
	[44] = {nTaskType = 0, szShow = "Thu thËp Lôc PhØ Thóy Hé Th©n phï hÖ Kim [ Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[44]}},
	[45] = {nTaskType = 0, szShow = "Thu thËp D­¬ng ChØ B¹ch Ngäc hÖ Thñy [Ngäc Béi CÊp 10].", tbList = {allbrother_0801_tbItemList[19]}},
	[46] = {nTaskType = 0, szShow = "Thu thËp ¢m Du¬ng V« Cùc qu¸n hÖ Háa [Nãn CÊp 10]", tbList = {allbrother_0801_tbItemList[45]}},
	[47] = {nTaskType = 0, szShow = "Thu thËp Toµn Th¹ch H¹ng Liªn hÖ Thñy [Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[46]}},
	[48] = {nTaskType = 0, szShow = "Thu thËp Long Tiªn Hu¬ng Nang hÖ Thæ [ Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[47]}},
	[49] = {nTaskType = 0, szShow = "Thu thËp Ph¸ Thiªn chïy hÖ Kim [Vò KhÝ CÊp 10]", tbList = {allbrother_0801_tbItemList[48]}},
	[50] = {nTaskType = 0, szShow = "Thu thËp ®å phæ hoµng kim - §Þnh Quèc Thanh Sa Tr­êng Sam [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[49]} },
	[51] = {nTaskType = 0, szShow = "Thu thËp ®å phæ hoµng kim - §Þnh Quèc Ng©n Tµm Yªu ®¸i [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[50]} },
	[52] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þnh Quèc ¤ Sa Ph¸t Qu¸n [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[51]} },
	[53] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þnh Quèc XÝch Quyªn NhuyÔn Ngoa [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[52]} },
	[54] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þnh Quèc Tö §»ng Hé UyÓn [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[53]} },
	[55] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - Méng Long Kim Ti ChÝnh Hång Cµ Sa [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[54]} },
	[56] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - Chó Ph­îc DiÖt L«i C¶nh Phï [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[55]} },
	[57] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - U Lung MÆc Thï NhuyÔn Lý [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[56]} },
	[58] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - §Þa Ph¸ch H¾c DiÖm Xung Thiªn Liªn [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[57]} },
	[59] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - BÝch H¶i Uyªn ¦¬ng Liªn Hoµn §ao [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[58]} },
	[60] = {nTaskType = 0, szShow = "Thu thËp ®å phæ Hoµng Kim - V« TrÇn Thanh T©m H­íng ThiÖn Ch©u [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[59]} },
	[61] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 1 [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[60]} },
	[62] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 2 [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[61]} },
	[63] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 3 [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[62]} },
	[64] = {nTaskType = 0, szShow = "Thu thËp TrÊn bang chi th¹ch cÊp 4 [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[63]} },
	[65] = {nTaskType = 0, szShow = "Thu thËp Kh¸ng ®¬n chi gi¸c [Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[64]} },
	[66] = {nTaskType = 0, szShow = "Thu thËp SÜ binh chi hiÖu gi¸c [ Thuèc Tèng Kim] ", tbList = {allbrother_0801_tbItemList[65]} },
	[67] = {nTaskType = 0, szShow = "Thu thËp Bå c©u [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[66]} },
	[68] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ngo¹i ®éc hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[67]} },
	[69] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ngo¹i b¨ng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[68]} },
	[70] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ngo¹i phæ hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[69]} },
	[71] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi b¨ng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[70]} },
	[72] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi phæ hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[71]} },
	[73] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi ®éc hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[72]} },
	[74] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi l«i hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[73]} },
	[75] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim néi háa hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[74]} },
	[76] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim tr­êng mÖnh hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[75]} },
	[77] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim gia bµo hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[76]} },
	[78] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim cao thiÓm hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[77]} },
	[79] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim cao trung hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[78]} },
	[80] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim phi tèc hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[79]} },
	[81] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim phæ phßng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[80]} },
	[82] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim b¨ng phßng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[81]} },
	[83] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim l«i phßng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[82]} },
	[84] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim háa phßng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[83]} },
	[85] = {nTaskType = 0, szShow = "Thu thËp Tèng Kim ®éc phßng hoµn [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[84]} },
	[86] = {nTaskType = 0, szShow = "Thu thËp Cµn kh«n t¹o hãa ®an (tiÓu) [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[85]} },
	[87] = {nTaskType = 0, szShow = "Thu thËp Cµn kh«n t¹o hãa ®an (trung) [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[86]} },
	[88] = {nTaskType = 0, szShow = "Thu thËp Cµn kh«n t¹o hãa ®an (®¹i) [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[87]} },
	[89] = {nTaskType = 0, szShow = "Thu thËp ChiÕn cæ [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[88]} },
	[90] = {nTaskType = 0, szShow = "Thu thËp LÖnh bµi [ Tèng Kim]", tbList = {allbrother_0801_tbItemList[89]} },
	[91] = {nTaskType = 0, szShow = "Thu thËp 10 huyÒn tinh kho¸ng th¹ch (cÊp 1) [ ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[90]} },
	[92] = {nTaskType = 0, szShow = "Thu thËp 10 huyÒn tinh kho¸ng th¹ch (cÊp 2) [ ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[91]} },
	[93] = {nTaskType = 0, szShow = "Thu thËp 5 huyÒn tinh kho¸ng th¹ch (cÊp 3) [ ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[92]} },
	[94] = {nTaskType = 0, szShow = "Thu thËp 1 huyÒn tinh kho¸ng th¹ch (cÊp 4) [ ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[93]} },
	[95] = {nTaskType = 0, szShow = "Thu thËp ThÝ Gi¶ Chi Ên [ Thuèc Tèng Kim]", tbList = {allbrother_0801_tbItemList[94]} },
	[96] = {nTaskType = 0, szShow = "Thu thËp 20 Khiªu chiÕn lÖnh [ Khã Bá Qua §i]", tbList = {allbrother_0801_tbItemList[95]} },
	[97] = {nTaskType = 0, szShow = "Thu thËp 2 Thiªn s¬n b¶o lé [ ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[96]} },
	[98] = {nTaskType = 0, szShow = "Thu thËp B¸ch qu¶ lé [ ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[97]} },
	[99] = {nTaskType = 0, szShow = "Thu thËp lÖnh bµi Phong L¨ng §é [T¹p Hãa Thµnh ThÞ]", tbList = {allbrother_0801_tbItemList[98]} },
	[100] = {nTaskType = 0, szShow = "Thu thËp HiÖp cèt chi ®an t©m giíi [Shop B¾c §Èu] ", tbList = {allbrother_0801_tbItemList[99]} },
	[101] = {nTaskType = 0, szShow = "Thu thËp HiÖp cèt ®a t×nh hoµn [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[100]} },
	[102] = {nTaskType = 0, szShow = "Thu thËp Nhu t×nh phông nghi giíi chØ [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[101]} },
	[103] = {nTaskType = 0, szShow = "Thu thËp Nhu t×nh thôc n÷ h¹ng liªn [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[102]} },
	[104] = {nTaskType = 0, szShow = "Thu thËp §Þnh quèc tö ®»ng hé uyÓn [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[103]} },
	[105] = {nTaskType = 0, szShow = "Thu thËp §Þnh quèc ng©n tµm yªu ®¸i [Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[104]} },
	[106] = {nTaskType = 0, szShow = "Thu thËp HuyÒn thiÕt kho¸ng [§¸ Ðp §å TÝm Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[105]} },
	[107] = {nTaskType = 0, szShow = "Thu thËp Khæng t­íc th¹ch [§¸ Ðp §å TÝm Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[106]} },
	[108] = {nTaskType = 0, szShow = "Thu thËp MËt ng©n kho¸ng [§¸ Ðp §å TÝm Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[107]} },
	[109] = {nTaskType = 0, szShow = "Thu thËp Phï dung th¹ch [§¸ Ðp §å TÝm Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[108]} },
	[110] = {nTaskType = 0, szShow = "Thu thËp Chu sa th¹ch [§¸ Ðp §å TÝm Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[109]} },
	[111] = {nTaskType = 0, szShow = "Thu thËp Chung nhò th¹ch[§¸ Ðp §å TÝm Shop B¾c §Èu]", tbList = {allbrother_0801_tbItemList[110]} },
	[112] = {nTaskType = 0, szShow = "Thu thËp ThiÕt la h¸n [ Shop B¾c §Èu [Tèng Kim]", tbList = {allbrother_0801_tbItemList[111]} },
	[113] = {nTaskType = 0, szShow = "Thu thËp Bµn nh­îc t©m kinh [ Shop B¾c §Èu [Tèng Kim]", tbList = {allbrother_0801_tbItemList[112]} },
	[114] = {nTaskType = 0, szShow = "Thu thËp DiÖt kiÕm mËt tÞch [BÝ KiÕp Nga My [KiÕm] ", tbList = {allbrother_0801_tbItemList[113]} },
	[115] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn ®ao ph¸p [BÝ KiÕp Thóy Yªn [§ao]", tbList = {allbrother_0801_tbItemList[114]} },
	[116] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn song ®ao [BÝ KiÕp Thóy Yªn [Song §ao]", tbList = {allbrother_0801_tbItemList[115]} },
	[117] = {nTaskType = 0, szShow = "Thu thËp C¸i bang ch­ëng ph¸p [BÝ KiÕp C¸i Bang [Rång]", tbList = {allbrother_0801_tbItemList[116]} },
	[118] = {nTaskType = 0, szShow = "Thu thËp C¸i bang c«n ph¸p [BÝ KiÕp C¸i Bang [Bæng]", tbList = {allbrother_0801_tbItemList[117]} },
	[119] = {nTaskType = 0, szShow = "Thu thËp Thiªn V­¬ng chïy ph¸p quyÓn 1 [ BÝ KiÕp Thiªn V­¬ng [Chïy]", tbList = {allbrother_0801_tbItemList[118]} },
	[120] = {nTaskType = 0, szShow = "Thu thËp Thiªn V­¬ng th­¬ng ph¸p quyÓn 2 [BÝ KiÕp Thiªn V­¬ng [Th­¬ng]", tbList = {allbrother_0801_tbItemList[119]} },
	[121] = {nTaskType = 0, szShow = "Thu thËp Thiªn V­¬ng ®ao ph¸p quyÓn 3 [BÝ KiÕp Thiªn V­¬ng [§ao]", tbList = {allbrother_0801_tbItemList[120]} },
	[122] = {nTaskType = 0, szShow = "Thu thËp ThiÕu l©m quyÒn ph¸p quyÓn 1 [ BÝ KiÕp ThiÕu L©m [QuyÒn Ph¸p]", tbList = {allbrother_0801_tbItemList[121]} },
	[123] = {nTaskType = 0, szShow = "Thu thËp ThiÕu l©m c«n ph¸p quyÓn 2 [BÝ KiÕp ThiÕu L©m [C«n Ph¸p]", tbList = {allbrother_0801_tbItemList[122]} },
	[124] = {nTaskType = 0, szShow = "Thu thËp ThiÕu l©m ®ao ph¸p quyÓn 3 [BÝ KiÕp Thiªu L©m [§ao Ph¸p]", tbList = {allbrother_0801_tbItemList[123]} },
	[125] = {nTaskType = 0, szShow = "Thu thËp Phi ®ao thuËt (NhiÕp hån nguyÖt ¶nh) [BÝ KiÕp §­êng M«n [NhiÕp Hån]", tbList = {allbrother_0801_tbItemList[124]} },
	[126] = {nTaskType = 0, szShow = "Thu thËp Phi tiªu thuËt (Cöu cung phi tinh) [BÝ KiÕp §­êng M«n [C÷u Cung]", tbList = {allbrother_0801_tbItemList[125]} },
	[127] = {nTaskType = 0, szShow = "Thu thËp Tô tiÔn ThuËt (B¹o Vò Lª Hoa) [BÝ KiÕp §­êng M«n [Nâ]", tbList = {allbrother_0801_tbItemList[126]} },
	[128] = {nTaskType = 0, szShow = "Thu thËp H·m TÜnh ThuËt (Lo¹n Hoµn KÝch) [BÝ KiÕp §­êng M«n §Æt [B¶y]", tbList = {allbrother_0801_tbItemList[127]} },
	[129] = {nTaskType = 0, szShow = "Thu thËp Ngò ®éc ch­ëng ph¸p quyÓn 1 [BÝ KiÕp Ngò [§éc Ch­ëng]", tbList = {allbrother_0801_tbItemList[128]} },
	[130] = {nTaskType = 0, szShow = "Thu thËp Ngò ®éc ®ao ph¸p quyÓn 2 [BÝ KiÕp Ngò §éc [§ao]", tbList = {allbrother_0801_tbItemList[129]} },
	[131] = {nTaskType = 0, szShow = "Thu thËp Ngò ®éc nhiÕp t©m thuËt quyÓn 3 [ BÝ KiÕp Ngò §éc [Bïa]", tbList = {allbrother_0801_tbItemList[130]} },
	[132] = {nTaskType = 0, szShow = "Thu thËp DiÖt kiÕm mËt tÞch [BÝ KiÕp Nga My [KiÕm]", tbList = {allbrother_0801_tbItemList[131]} },
	[133] = {nTaskType = 0, szShow = "Thu thËp Nga My phËt quang ch­ëng mËt tÞch [BÝ KiÕp Nga My [Ch­ëng]", tbList = {allbrother_0801_tbItemList[132]} },
	[134] = {nTaskType = 0, szShow = "Thu thËp phæ ®é mËt tÞch [BÝ KiÕp Nga My [Buff]", tbList = {allbrother_0801_tbItemList[133]} },
	[135] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn ®ao ph¸p [BÝ KiÕp Thóy Yªn [§ao]", tbList = {allbrother_0801_tbItemList[134]} },
	[136] = {nTaskType = 0, szShow = "Thu thËp Thóy Yªn song ®ao [BÝ KiÕp Thóy Yªn Song [§ao]", tbList = {allbrother_0801_tbItemList[135]} },
	[137] = {nTaskType = 0, szShow = "Thu thËp C¸i bang ch­ëng ph¸p [BÝ KiÕp C¸i Bang [Ch­ëng]", tbList = {allbrother_0801_tbItemList[136]} },
	[138] = {nTaskType = 0, szShow = "Thu thËp C¸i bang c«n ph¸p [BÝ KiÕp C¸i Bang [Bæng]", tbList = {allbrother_0801_tbItemList[137]} },
	[139] = {nTaskType = 0, szShow = "Thu thËp V©n Long kÝch (M©u ph¸p) [BÝ KiÕp Thiªn NhÉn [KÝch]", tbList = {allbrother_0801_tbItemList[138]} },
	[140] = {nTaskType = 0, szShow = "Thu thËp L­u tinh (§ao ph¸p) [BÝ KiÕp Thiªn NhÉn [§ao]", tbList = {allbrother_0801_tbItemList[139]} },
	[141] = {nTaskType = 0, szShow = "Thu thËp NhiÕp hån (Chó thuËt) [BÝ KiÕp Thiªn NhÉn [Bïa]", tbList = {allbrother_0801_tbItemList[140]} },
	[142] = {nTaskType = 0, szShow = "Thu thËp Th¸i cùc quyÒn phæ quyÓn 3 [BÝ KiÕp Vâ §ang [QuyÒn]", tbList = {allbrother_0801_tbItemList[141]} },
	[143] = {nTaskType = 0, szShow = "Thu thËp Th¸i cùc kiÕm phæ quyÓn 2 [BÝ KiÕp Vâ §ang[KiÕm]", tbList = {allbrother_0801_tbItemList[142]} },
	[144] = {nTaskType = 0, szShow = "Thu thËp Ngù phong thuËt [BÝ KiÕp C«n L«n [§ao]", tbList = {allbrother_0801_tbItemList[143]} },
	[145] = {nTaskType = 0, szShow = "Thu thËp Ngù l«i thuËt [BÝ KiÕp C«n L«n [KiÕm]", tbList = {allbrother_0801_tbItemList[144]} },
	[146] = {nTaskType = 0, szShow = "Thu thËp Ngù t©m thuËt [BÝ KiÕp C«n L«n [Bïa]", tbList = {allbrother_0801_tbItemList[145]} },
	[147] = {nTaskType = 0, szShow = "Thu thËp LiÖt hång m· [ B¸n Ngùa [Thµnh §«] CÊp 1, D­¬ng chØ b¹ch ngäc (hÖ háa) [Ngäc Béi CÊp 10] ", tbList = {allbrother_0801_tbItemList[146], allbrother_0801_tbItemList[180] }},
	[148] = {nTaskType = 0, szShow = "Thu thËp Hång m· [ B¸n Ngùa [Thµnh §«] CÊp 4, Lôc phØ thóy hé th©n phô (hÖ méc) [Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[147], allbrother_0801_tbItemList[181] }},
	[149] = {nTaskType = 0, szShow = "Thu thËp Hång li [B¸n Ngùa [Thµnh §«] CÊp 6, Toµn th¹ch giíi chØ (hÖ kim) [ NhÉn CÊp 10]", tbList = {allbrother_0801_tbItemList[148], allbrother_0801_tbItemList[43] }},
	[150] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn h·n huyÕt m· [B¸n Ngùa [Thµnh §«] CÊp 7, Toµn th¹ch giíi chØ (hÖ kim) [NhÉn CÊp 10] ", tbList = {allbrother_0801_tbItemList[149], allbrother_0801_tbItemList[43] }},
	[151] = {nTaskType = 0, szShow = "Thu thËp XÝch Kþ [B¸n Ngùa [Thµnh §«] CÊp 9 , D­¬ng chØ b¹ch ngäc (hÖ háa) [ Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[150], allbrother_0801_tbItemList[180] }},
	[152] = {nTaskType = 0, szShow = "Thu thËp LiÖt h¾c m· [ B¸n Ngùa [T­¬ng D­¬ng] CÊp 1 , Phi phong [ThÇn BÝ Th­¬ng Nh©n[T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[151], allbrother_0801_tbItemList[183] }},
	[153] = {nTaskType = 0, szShow = "Thu thËp H¾c m· [ B¸n Ngùa [T­¬ng D­¬ng] CÊp 4, D­¬ng chØ b¹ch ngäc (hÖ méc) [Ngoc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[152], allbrother_0801_tbItemList[184] }},
	[154] = {nTaskType = 0, szShow = "Thu thËp H¾c kú [ B¸n Ngùa [T­¬ng D­¬ng] CÊp 5, B¸ch qu¶ lé [ThÇn Bi Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[153], allbrother_0801_tbItemList[97] }},
	[155] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn h¾c m· [B¸n Ngùa [T­¬ng D­¬ng] CÊp 7, Lôc phØ thóy hé th©n phï (hÖ kim)", tbList = {allbrother_0801_tbItemList[154], allbrother_0801_tbItemList[44] }},
	[156] = {nTaskType = 0, szShow = "Thu thËp ¤ truy [B¸n Ngùa [§¹i Lý] , Toµn th¹ch giíi chØ (hÖ méc) [NhÉn CÊp 10]", tbList = {allbrother_0801_tbItemList[155], allbrother_0801_tbItemList[185] }},
	[157] = {nTaskType = 0, szShow = "Thu thËp LiÖt b¹ch m·  [B¸n Ngùa [Ph­îng T­êng] CÊp 1 , Toµn th¹ch h¹ng liªn (hÖ méc) [Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[156], allbrother_0801_tbItemList[186] }},
	[158] = {nTaskType = 0, szShow = "Thu thËp B¹ch m· [B¸n Ngùa [Ph­îng T­êng] CÊp 4 , Long tiªn h­¬ng nang (hÖ thñy) [Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[157], allbrother_0801_tbItemList[187] }},
	[159] = {nTaskType = 0, szShow = "Thu thËp Ngäc hoa th«ng [B¸n Ngùa [Ph­îng T­êng] CÊp 5, Phi phong [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[158], allbrother_0801_tbItemList[183] }},
	[160] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn b¹ch m· [B¸n Ngùa [Ph­îng T­êng] CÊp 7, D­¬ng chi b¹ch ngäc (hÖ kim) [Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[30], allbrother_0801_tbItemList[188] }},
	[161] = {nTaskType = 0, szShow = "Thu thËp Tóc s­¬ng [B¸n Ngùa [Ph­îng T­êng] CÊp 10, Lôc phØ thóy hé th©n phï (hÖ háa) [Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[5], allbrother_0801_tbItemList[189] }},
	[162] = {nTaskType = 0, szShow = "Thu thËp LiÖt hoµn m· [B¸n Ngùa [L©m An] C©p 1, Toµn th¹ch giíi chØ (hÖ thñy) [NhÉn CÊp 10]", tbList = {allbrother_0801_tbItemList[159], allbrother_0801_tbItemList[2] }},
	[163] = {nTaskType = 0, szShow = "Thu thËp Hoµng m· [B¸n Ngùa [L©m An] C©p 4, Toµn th¹ch h¹ng liªn (hÖ thñy)[Gi©y ChuyÒn CÊp 10] ", tbList = {allbrother_0801_tbItemList[160], allbrother_0801_tbItemList[46] }},
	[164] = {nTaskType = 0, szShow = "Thu thËp Hoµng phiªu  [B¸n Ngùa [L©m An] C©p 5, Long tiªn h­¬ng nang (hÖ méc) [Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[162], allbrother_0801_tbItemList[1] }},
	[165] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn hoµng m· [B¸n Ngùa [L©m An] C©p 7, D­¬ng chi b¹ch ngäc (hÖ thæ) [Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[161], allbrother_0801_tbItemList[191] }},
	[166] = {nTaskType = 0, szShow = "Thu thËp Phi hoµng [B¸n Ngùa [L©m An] C©p 10, Phi phong [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng]", tbList = {allbrother_0801_tbItemList[163], allbrother_0801_tbItemList[183] }},
	[167] = {nTaskType = 0, szShow = "Thu thËp LiÖt thanh m· [B¸n Ngùa [D­¬ng Ch©u] CÊp 1, Toµn th¹ch giíi chØ (hÖ háa) [NhÉn CÊp 10]", tbList = {allbrother_0801_tbItemList[164], allbrother_0801_tbItemList[192] }},
	[168] = {nTaskType = 0, szShow = "Thu thËp Thanh th«ng [B¸n Ngùa [D­¬ng Ch©u] CÊp 4, Phi phong [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[165], allbrother_0801_tbItemList[183] }},
	[169] = {nTaskType = 0, szShow = "Thu thËp Tö l­u [B¸n Ngùa [D­¬ng Ch©u] CÊp 5, B¸ch qu¶ lé [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[166], allbrother_0801_tbItemList[97] }},
	[170] = {nTaskType = 0, szShow = "Thu thËp §¹i uyÓn thanh m· [B¸n Ngùa [D­¬ng Ch©u] CÊp 8 , Toµn th¹ch h¹ng liªn (hÖ kim) [Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[167], allbrother_0801_tbItemList[193] }},
	[171] = {nTaskType = 0, szShow = "Thu thËp Ph¸ thiªn kÝch (hÖ thñy) [Vò KhÝ CÊp 10], Phi phong [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[169], allbrother_0801_tbItemList[183] }},
	[172] = {nTaskType = 0, szShow = "Thu thËp HuyÒn thiÕt kiÕm (hÖ thæ) [Vò KhÝ CÊp 10] , D­¬ng chi b¹ch ngäc (hÖ thñy) [Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[34], allbrother_0801_tbItemList[19] }},
	[173] = {nTaskType = 0, szShow = "Thu thËp Kim c« bæng (hÖ kim) [Vò KhÝ CÊp 10] , B¸ch qu¶ lé [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[171], allbrother_0801_tbItemList[97] }},
	[174] = {nTaskType = 0, szShow = "Thu thËp Th«n nhËt tr¶m (hÖ thñy) [Vò KhÝ CÊp 10] , Long tiªn h­¬ng nang (hÖ háa) [Ngäc Béi CÊp 10]", tbList = {allbrother_0801_tbItemList[172], allbrother_0801_tbItemList[194] }},
	[175] = {nTaskType = 0, szShow = "Thu thËp §¹i phong ®ao (hÖ háa) [Vò KhÝ CÊp 10] , Toµn th¹ch giíi chØ (hÖ thæ) [NhÉn CÊp 10] ", tbList = {allbrother_0801_tbItemList[173], allbrother_0801_tbItemList[195] }},
	[176] = {nTaskType = 0, szShow = "Thu thËp Ph¸ thiªn chïy (hÖ kim) [Vò KhÝ CÊp 10] , Toµn th¹ch h¹ng liªn (hÖ háa) [Gi©y ChuyÒn CÊp 10] ", tbList = {allbrother_0801_tbItemList[48], allbrother_0801_tbItemList[196] }},
	[177] = {nTaskType = 0, szShow = "Thu thËp Ng­ l¹p (hÖ kim) [T¹p Hãa [3 Lang HuyÖn] , B¸ch qu¶ lé [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[23], allbrother_0801_tbItemList[97] }},
	[178] = {nTaskType = 0, szShow = "Thu thËp To¸n ®Çu chïy (hÖ kim) [Thî RÌn [3 Lang HuyÖn] , Lôc phØ thóy hé th©n phï (hÖ thñy) [Gi©y ChuyÒn CÊp 10] ", tbList = {allbrother_0801_tbItemList[176], allbrother_0801_tbItemList[190] }},
	[179] = {nTaskType = 0, szShow = "Thu thËp Tr­êng th­¬ng (hÖ thñy) [Thî RÌn [Ph­îng T­êng], Phi phong [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[177], allbrother_0801_tbItemList[183] }},
	[180] = {nTaskType = 0, szShow = "Thu thËp NguyÖt nha thÝch (hÖ thñy) [Thî RÌn [§¹i Lý], B¸ch qu¶ lé [ThÇn BÝ Th­¬ng Nh©n [T­¬ng D­¬ng] ", tbList = {allbrother_0801_tbItemList[178], allbrother_0801_tbItemList[97] }},
	[181] = {nTaskType = 0, szShow = "Thu thËp T­îng b× hé uyÓn (hÖ kim)  [T¹p Hãa [Ph­îng T­êng] , Lôc phØ thóy hé th©n phï (hÖ thæ) [ Gi©y ChuyÒn CÊp 10]", tbList = {allbrother_0801_tbItemList[179], allbrother_0801_tbItemList[175] }},
	[182] = {nTaskType = 1, szShow = "§Õn T­¬ng D­¬ng t×m ¤ng chñ Hµ [Täa §é 195/203]"},
	[183] = {nTaskType = 1, szShow = "§Õn T­¬ng D­¬ng t×m Qu¸ch viªn ngo¹i [Täa §é 197/207]"},
	[184] = {nTaskType = 1, szShow = "§Õn T­¬ng D­¬ng t×m Ph¹m NhÞ Xu©n [Täa §é 193/194]"},
	[185] = {nTaskType = 1, szShow = "§Õn Thµnh §« t×m T©n NhÞ ThÈm [Täa §é 378/317]"},
	[186] = {nTaskType = 1, szShow = "§Õn Thµnh §« t×m Tèng cö nh©n [Täa §é 193/194]"},
	[187] = {nTaskType = 1, szShow = "§Õn §¹i Lý t×m §ao Liªn Anh [Täa §é 202/198]"},
	[188] = {nTaskType = 1, szShow = "§Õn Ph­îng T­êng t×m Tiªu côc [Täa §é 192/199]"},
	[189] = {nTaskType = 1, szShow = "§Õn Ph­îng T­êng t×m Chu §å Phu [Täa §é 201/197]"},
	[190] = {nTaskType = 1, szShow = "§Õn BiÖn Kinh t×m §¹i §é ThiÒn S­ [Täa §é 214/186]"},
	[191] = {nTaskType = 1, szShow = "§Õn BiÖn Kinh t×m Anh Tö [Täa §é 225/194]"},
	[192] = {nTaskType = 1, szShow = "§Õn L©m An t×m T¹ §¹i Gia [Täa §é 174/192]"},
	[193] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u t×m TriÖu ®µ chñ [Täa §é 213/177"},
	[194] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u t×m Giang NhÊt Tiªu [Täa §é 203/192]"},
	[195] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u t×m «ng chñ §ç [Täa §é 207/199]"},
	[196] = {nTaskType = 1, szShow = "§Õn Giang T©n th«n t×m Qu¸ch Dòng [Täa §é 436/388]"},
	[197] = {nTaskType = 1, szShow = "§Õn Th¹ch Cæ trÊn t×m ThÈm gia [Täa §é 201/200]"},
	[198] = {nTaskType = 1, szShow = "§Õn VÜnh L¹c trÊn t×m bµ Th­ [Täa §é 205/206]"},
	[199] = {nTaskType = 1, szShow = "H·y ®Õn Long M«n trÊn t×m T«n NhÞ Lang! [Täa §é 251/284]"},
	[200] = {nTaskType = 1, szShow = "§Õn Ba L¨ng HuyÖn Ph­¬ng Kh¶ VÞ [Täa §é 195/199]"},
	[201] = {nTaskType = 1, szShow = "§Õn Nam Nh¹c TrÊn t×m §iÒn bµ bµ [Täa §é 207/192]"},
	[202] = {nTaskType = 1, szShow = "§Õn Chu Tiªn TrÊn Chñ L÷ Qu¸n [Täa §é 209/198]"},
	[203] = {nTaskType = 1, szShow = "§Õn Long TuyÒn Th«n t×m T« Hång Tô [Täa §é 203/204]"},
	[204] = {nTaskType = 1, szShow = "§Õn §¹o H­¬ng Th«n t×m chñ tiÖm trµ [Täa §é 208/203]"},
	[205] = {nTaskType = 1, szShow = "§Õn Thiªn V­¬ng bang t×m Ng­ Phô Hµ TÈu [Täa §é 190/213]"},
	[206] = {nTaskType = 1, szShow = "§Õn ThiÕu l©m ph¸i La H¸n §­êng t×m HuyÒn Nan [Täa §é 202/192]"},
	[207] = {nTaskType = 1, szShow = "§Õn Nga My ph¸i t×m DiÖu Èn T­íng C«ng [Täa §é 241/328]"},
	[208] = {nTaskType = 1, szShow = "§Õn Nga My ph¸i t×m DiÖu KhiÕt [Täa §é 242/307]"},
	[209] = {nTaskType = 1, szShow = "§Õn C¸i bang t×m Tõ Tam Tr­îng [Täa §é 189/236]"},
	[210] = {nTaskType = 1, szShow = "§Õn Thiªn NhÉn gi¸o tÇng 3 t×m Qu©n s­ [Täa §é 212/196]"},
	[211] = {nTaskType = 1, szShow = "§Õn §¹o H­¬ng Th«n T×m Hoa Hoa [Täa §é 213/203]"},
	[212] = {nTaskType = 1, szShow = "§Õn §¹o H­¬ng Th«n T×m TiÓu Long [Täa §é 195/201]"},
	[213] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u T×m Bµ Chñ TiÖm VËt Nu«i [Täa §é 223/193]"},
	[214] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u Töu LÇu T×m Tóy B¸n Tiªn [Täa §é 216/189]"},
	[215] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u T×m Tr­¬ng §¹i Nh©n [Täa §é 201/197]"},
	[216] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u T×m T«n Viªn Ngo¹i [Täa §é 202/190]"},
	[217] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u T×m LiÔu L·o Gia [Täa §é 207/201]"},
	[218] = {nTaskType = 1, szShow = "§Õn D­¬ng Ch©u T×m NhiÖm Thiªn Nhai [Täa §é 220/195]"},
	[219] = {nTaskType = 0, szShow = "Thu thËp 1 Viªn Long HuyÕt Hoµn [TRONG Kú TR¢N C¸C]", tbList = {allbrother_0801_tbItemList[197]} },
	[220] = {nTaskType = 0, szShow = "Thu thËp 1 Viªn H¶i Long Ch©u [TRONG Kú TR¢N C¸C]", tbList = {allbrother_0801_tbItemList[198]} },
	[221] = {nTaskType = 0, szShow = "Thu thËp 1 LÖnh Bµi Thñy TÆc [TRONG Kú TR¢N C¸C]", tbList = {allbrother_0801_tbItemList[199]} },
	[222] = {nTaskType = 0, szShow = "Thu thËp 1 Thiªn B¶o Khè LÖnh [TRONG Kú TR¢N C¸C]", tbList = {allbrother_0801_tbItemList[200]} },
	[223] = {nTaskType = 1, szShow = "H·y §Õn Thµnh §« T×m Tõ TÈu [Täa §é 399/316]"},
	[224] = {nTaskType = 1, szShow = "H·y §Õn Thµnh §å T×m Xu©n C« [Täa §é 403/314]"},
	[225] = {nTaskType = 1, szShow = "H·y §Õn Thµnh §« T×m TiÓu Hçn Hçn [Täa §é 385/313]"},
	[226] = {nTaskType = 1, szShow = "H·y §Õn Thµnh §« T×m T«n UyÓn [Täa §é 394/323]"},
	[227] = {nTaskType = 1, szShow = "H·y §Õn Thµnh §« T×m Tiªu Bµ Bµ [Täa §é 388/313]"},
}

function allbrother_0801_CompleteTask()
	local nTaskState = GetTask(TSK_StartNhiemVu_TaskState)
	local nTaskTime = GetTask(TSK_StartTime_TaskTime)
	
	if nTaskTime + TSKV_StartTime_TaskTime <= GetCurServerTime() then 
		SetTask(TSK_StartNhiemVu_TaskState, 0)
		Msg2Player("Thêi gian hoµn thµnh nhiÖm vô ®· hÕt, nhiÖm vô thÊt b¹i!")
		return 0
	else
		nTaskState = nTaskState + 1073741824 
		SetTask(TSK_StartNhiemVu_TaskState, nTaskState)
		Msg2Player("Hoµn Thµnh NhiÖm Vô B¾c §Èu L·o Nh©n Giao Cho.")
		return 1;
	end
	
end
