roll_cfg =  {
	[1] = {

		{"hang lien",3405},
		{"non",3406},
		{"Nhan tren",3407},
		{"Ho uyen",3408},
		{"Dai lung",3409},
		{"Ao",3410},
		{"Vu khi",3411},
		{"day",3412},
		{"Ngoc boi",3413},
		{"Nhan duoi",3414},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• PhÃ‹t ChÂ©u",3415},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• TÂ¨ng MÂ¹o",3416},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• Â§Â¹i TÃµ ChÃ˜ HoÂµn",3417},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• HÃ© UyÃ“n",3418},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• YÂªu Â§Â¸i",3419},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• CÂµ Sa",3420},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• PhÂ¸p CÂ«n",3421},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• TÂ¨ng HÂµi",3422},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• YÂªu TrÃ´y",3423},
		{"Tinh SÂ­Â¬ng DiÃ–t Â§Ã• Â§Â¹i Bi ChÃ˜ HoÂµn",3424},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• HÂ¹ng LiÂªn",3425},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• TÂ¨ng MÂ¹o",3426},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• Â§Â¹i ThÃµa ChÃ˜ HoÂµn",3427},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• HÃ© UyÃ“n",3428},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• YÂªu Â§Â¸i",3429},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• CÂµ Sa",3430},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• GiÃ­i Â§ao",3431},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• TÂ¨ng HÂµi",3432},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• YÂªu TrÃ´y",3433},
		{"Tinh SÂ­Â¬ng Â§Â¹o Â§Ã• TiÃ“u ThÃµa ChÃ˜ HoÂµn",3434},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ HÂ¹ng LiÂªn",3435},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ KhÂ«i",3436},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ NhÂ­ Ã½ ChÃ˜ HoÂµn",3437},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ ThÃ³c UyÃ“n",3438},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ YÂªu Â§Â¸i",3439},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ KhÂ¶i",3440},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ ThÃ‡n ChÃ¯y",3441},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ Ngoa",3442},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ QuÂ¶i TrÃ´y",3443},
		{"Tinh SÂ­Â¬ng ThÂ«n TÂµ TÃch TÂµ ChÃ˜ HoÂµn",3444},
		{"Tinh SÂ­Â¬ng LÂ­u Kim HÂ¹ng LiÂªn",3445},
		{"Tinh SÂ­Â¬ng LÂ­u Kim KhÂ«i",3446},
		{"Tinh SÂ­Â¬ng LÂ­u Kim Â§Âµn HÂ­Â¬ng ChÃ˜ HoÂµn",3447},
		{"Tinh SÂ­Â¬ng LÂ­u Kim ThÃ³c UyÃ“n",3448},
		{"Tinh SÂ­Â¬ng LÂ­u Kim YÂªu Â§Â¸i",3449},
		{"Tinh SÂ­Â¬ng LÂ­u Kim KhÂ¶i",3450},
		{"Tinh SÂ­Â¬ng LÂ­u Kim ThÂ­Â¬ng",3451},
		{"Tinh SÂ­Â¬ng LÂ­u Kim Ngoa",3452},
		{"Tinh SÂ­Â¬ng LÂ­u Kim YÂªu TrÃ´y",3453},
		{"Tinh SÂ­Â¬ng LÂ­u Kim TrÃ‡m HÂ­Â¬ng ChÃ˜ HoÂµn",3454},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng HÂ¹ng LiÂªn",3455},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng KhÂ«i",3456},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng Long Â§Â¶m ChÃ˜ HoÂµn",3457},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng ThÃ³c UyÃ“n",3458},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng YÂªu Â§Â¸i",3459},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng KhÂ¶i",3460},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng BÂ¶o Â§ao",3461},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng Ngoa",3462},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng YÂªu TrÃ´y",3463},
		{"Tinh SÂ­Â¬ng LÃ· SÂ­Â¬ng PhÂ­Ã®ng TÃ—nh ChÃ˜ HoÂµn",3464},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh ChÂ©u LiÂªn",3465},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh PhÂ¸t Â§Â¸i",3466},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh Minh ChÂ©u ChÃ˜ HoÂµn",3467},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh LÂ­u VÂ©n TÃ´",3468},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh Ti Â§Â¸i",3469},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh NghÂª ThÂ­Ãªng VÃ² Y",3470},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh BÂ¶o KiÃ•m",3471},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh LÃ·",3472},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh HÂ­Â¬ng Nang",3473},
		{"Tinh SÂ­Â¬ng LÂ¹c Anh BÃch NgÃ¤c ChÃ˜ HoÂµn",3474},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t ChÂ©u LiÂªn",3475},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t PhÂ¸t Â§Â¸i",3476},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t LÂ­u Li ChÃ˜ HoÂµn",3477},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t TuyÃ•t Â¶nh TÃ´",3478},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t Ti Â§Â¸i",3479},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t TuyÃ•t TiÂªu Y",3480},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t TriÃ’n ThÃ±",3481},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t Ngoa",3482},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t HÂ­Â¬ng Nang",3483},
		{"Tinh SÂ­Â¬ng PhÃŠt HuyÃ–t ThÃ±y Tinh ChÃ˜ HoÂµn",3484},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng ChÂ©u LiÂªn",3485},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng TrÂ©m",3486},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng TuyÃ•t NgÃ¤c ChÃ˜ HoÂµn",3487},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng CÃˆm TÃ³ HÃ© UyÃ“n",3488},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng YÂªu Â§Â¸i",3489},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng KhÃ«i La Sam",3490},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng BÂ¶o Â§ao",3491},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng Ngoa",3492},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng HÂ­Â¬ng Nang",3493},
		{"Tinh SÂ­Â¬ng ThiÂªn HÂ­Â¬ng MÃ†c NgÃ¤c ChÃ˜ HoÂµn",3494},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n ChÂ©u LiÂªn",3495},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n TrÂ©m",3496},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n Linh Lung ChÃ˜ HoÂµn",3497},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n Sinh Hoa ThÃ± TrÂ¹c",3498},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n Ti Â§Â¸i",3499},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n ThÂ¸i Â§iÃ–p Y",3500},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n UyÂªn Â¦Â¬ng Â§ao",3501},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n Ngoa",3502},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n HÂ­Â¬ng Nang",3503},
		{"Tinh SÂ­Â¬ng ThÂ¸i VÃ‹n San HÂ« ChÃ˜ HoÂµn",3504},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi HÂ¹ng LiÂªn",3505},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi PhÂ¸t Â§Â¸i",3506},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi HuyÃ•t TÃch ChÃ˜ HoÂµn",3507},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi HÃ© UyÃ“n",3508},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi YÂªu Â§Â¸i",3509},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi CÃ¦ Y",3510},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi TriÃ’n ThÃ±",3511},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi Ngoa",3512},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi YÂªu TrÃ´y",3513},
		{"Tinh SÂ­Â¬ng ThiÃ’m Phi KhÂ« LÂ©u ChÃ˜ HoÂµn",3514},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t HÂ¹ng LiÂªn",3515},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t PhÂ¸t Â§Â¸i",3516},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t HuyÃ’n Â¢m GiÃ­i",3517},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t HÃ© UyÃ“n",3518},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t YÂªu Â§Â¸i",3519},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t HÃ© GiÂ¸p",3520},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t HuyÃ•t NhÃ‹n",3521},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t Ngoa",3522},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t YÂªu TrÃ´y",3523},
		{"Tinh SÂ­Â¬ng PhÃ´ CÃ¨t HuyÃ’n U GiÃ­i",3524},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t HÂ¹ng LiÂªn",3525},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t QuÂ¸n",3526},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t Phi Hoa ChÃ˜ HoÂµn",3527},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t HÃ© UyÃ“n",3528},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t TriÃ’n YÂªu",3529},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t GiÂ¸p",3530},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t Phi Â§ao",3531},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t LÃ·",3532},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t BÃ©i",3533},
		{"Tinh SÂ­Â¬ng LÂ·nh HuyÃ•t TrÃch DiÃ–p ChÃ˜ HoÂµn",3534},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn HÂ¹ng LiÂªn",3530},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn QuÂ¸n",3536},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn Linh XÂµ ChÃ˜ HoÂµn",3537},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn HÃ© UyÃ“n",3538},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn ThÃ³c YÂªu",3539},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn GiÂ¸p Y",3540},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn TÃ´ TiÃ”n",3541},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn LÃ·",3542},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn YÂªu TrÃ´y",3543},
		{"Tinh SÂ­Â¬ng NÃ© LiÂªn Kim ThiÃ’m ChÃ˜ HoÂµn",3544},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh HÂ¹ng LiÂªn",3545},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh PhÂ¸t QuÂ¸n",3546},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh NhiÃ•p PhÂ¸ch ChÃ˜ HoÂµn",3547},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh HÃ© UyÃ“n",3548},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh ThÃ³c YÂªu",3549},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh GiÂ¸p Y",3550},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh Phi TiÂªu",3551},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh LÃ·",3552},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh YÂªu TrÃ´y",3553},
		{"Tinh SÂ­Â¬ng Truy MÃ–nh Â§oÂ¹t HÃ¥n ChÃ˜ HoÂµn",3554},
		{"Tinh SÂ­Â¬ng MÂ·nh Long HÂ¹ng LiÂªn",3555},
		{"Tinh SÂ­Â¬ng MÂ·nh Long Â§Ã‡u HoÂµn",3556},
		{"Tinh SÂ­Â¬ng MÂ·nh Long VÂ¹n TrÂ­Ã®ng ChÃ˜ HoÂµn",3557},
		{"Tinh SÂ­Â¬ng MÂ·nh Long HÃ© UyÃ“n",3558},
		{"Tinh SÂ­Â¬ng MÂ·nh Long ThÃ³c YÂªu",3559},
		{"Tinh SÂ­Â¬ng MÂ·nh Long CÂ¸i Y",3560},
		{"Tinh SÂ­Â¬ng MÂ·nh Long TriÃ’n ThÃ±",3561},
		{"Tinh SÂ­Â¬ng MÂ·nh Long Ngoa",3562},
		{"Tinh SÂ­Â¬ng MÂ·nh Long YÂªu TrÃ´y",3563},
		{"Tinh SÂ­Â¬ng MÂ·nh Long ThiÂªn LÃ ChÃ˜ HoÂµn",3564},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ HÂ¹ng LiÂªn",3565},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ Â§Ã‡u HoÂµn",3566},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ LÃ´c Long Ban ChÃ˜",3567},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ HÃ© UyÃ“n",3568},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ ThÃ³c YÂªu",3569},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ CÂ¸i Y",3570},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ TrÂ­Ã®ng",3571},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ Ngoa",3572},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ YÂªu TrÃ´y",3573},
		{"Tinh SÂ­Â¬ng PhÂ¸ LÃ§ Linh ThÂ¹ch Ban ChÃ˜",3574},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t HÂ¹ng QuyÃ“n",3575},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t KhÂ«i",3576},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t LiÃ–t DiÃ”m Ban ChÃ˜",3577},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t HÃ© UyÃ“n",3578},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t YÂªu Â§Â¸i",3579},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t GiÂ¸p",3580},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t ThÂ­Â¬ng",3581},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t Ngoa",3582},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t BÃ©i",3583},
		{"Tinh SÂ­Â¬ng LuyÃ–n NhÃ‹t HuyÃ•t ThÃ³ Ban ChÃ˜",3584},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm HÂ¹ng LiÂªn",3585},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm QuÂ¸n MiÃ–n",3586},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm Dong Nham ChÃ˜ HoÂµn",3587},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm HÃ© UyÃ“n",3588},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm YÂªu Â§Â¸i",3589},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm GiÂ¸p Y",3590},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm BÂ¶o Â§ao",3591},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm Ngoa",3592},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm BÃ©i",3593},
		{"Tinh SÂ­Â¬ng KhÃ¨c ViÂªm DÂ­Â¬ng ViÂªm ChÃ˜ HoÂµn",3594},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n PhÃ¯",3595},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n QuÂ¸n",3596},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n VÃœnh Sinh ChÃ˜ HoÂµn",3597},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n TÃ´",3598},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n PhÂ¸p Â§Â¸i",3599},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n Â§Â¹o BÂµo",3600},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n ThÃ‡n KiÃ•m",3601},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n LÃ·",3602},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n NgÃ¤c BÃ©i",3603},
		{"Tinh SÂ­Â¬ng ChÃŠn SÂ¬n Â§Â¹o HÂµnh ChÃ˜ HoÂµn",3604},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy PhÃ¯",3605},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy QuÂ¸n",3606},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy HÂ»ng CÃ¶u PhÂ¸p GiÃ­i",3607},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy TÃ´",3608},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy PhÂ¸p Â§Â¸i",3609},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy Â§Â¹o BÂµo",3610},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy ThÃ‡n KiÃ•m",3611},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy LÃ·",3612},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy NgÃ¤c BÃ©i",3613},
		{"Tinh SÂ­Â¬ng QuÂ©n Uy BÃŠt DiÃ–t PhÂ¸p GiÃ­i",3614},
		{"Tinh SÂ­Â¬ng Minh LÂ«i HÂ¹ng LiÂªn",3615},
		{"Tinh SÂ­Â¬ng Minh LÂ«i Â§Â¹o QuÂ¸n",3616},
		{"Tinh SÂ­Â¬ng Minh LÂ«i TrÃ¤ng DÂ­Â¬ng GiÃ­i",3617},
		{"Tinh SÂ­Â¬ng Minh LÂ«i HÃ© UyÃ“n",3618},
		{"Tinh SÂ­Â¬ng Minh LÂ«i YÂªu Â§Â¸i",3619},
		{"Tinh SÂ­Â¬ng Minh LÂ«i Â§Â¹o BÂµo",3620},
		{"Tinh SÂ­Â¬ng Minh LÂ«i BÂ¶o Â§ao",3621},
		{"Tinh SÂ­Â¬ng Minh LÂ«i Ngoa",3622},
		{"Tinh SÂ­Â¬ng Minh LÂ«i BÃ©i",3623},
		{"Tinh SÂ­Â¬ng Minh LÂ«i CÂµn KhÂ«n GiÃ­i",3624},
		{"Tinh SÂ­Â¬ng Oanh Minh PhÃ¯",3625},
		{"Tinh SÂ­Â¬ng Oanh Minh Â§Â¹o QuÂ¸n",3626},
		{"Tinh SÂ­Â¬ng Oanh Minh Linh NgÃ¤c ChÃ˜ HoÂµn",3627},
		{"Tinh SÂ­Â¬ng Oanh Minh HÃ© UyÃ“n",3628},
		{"Tinh SÂ­Â¬ng Oanh Minh YÂªu Â§Â¸i",3629},
		{"Tinh SÂ­Â¬ng Oanh Minh Â§Â¹o BÂµo",3630},
		{"Tinh SÂ­Â¬ng Oanh Minh ThÃ‡n KiÃ•m",3631},
		{"Tinh SÂ­Â¬ng Oanh Minh Ngoa",3632},
		{"Tinh SÂ­Â¬ng Oanh Minh BÃ©i",3633},
		{"Tinh SÂ­Â¬ng Oanh Minh DÂ­Â¬ng Chi ChÃ˜ HoÂµn",3634},
		{"hang lien",3635},
		{"non",3636},
		{"Nhan tren",3637},
		{"Ho uyen",3638},
		{"Dai lung",3639},
		{"Ao",3640},
		{"Vu khi",3641},
		{"day",3642},
		{"Ngoc boi",3643},
		{"Nhan duoi",3644},
		{"hang lien",3645},
		{"non",3646},
		{"Nhan tren",3647},
		{"Ho uyen",3648},
		{"Dai lung",3649},
		{"Ao",3650},
		{"Vu khi",3651},
		{"day",3652},
		{"Ngoc boi",3653},
		{"Nhan duoi",3654}



},
	
	[2] = {
		{"B¶o r­¬ng tinh s­¬ng h¹ng liªn", 4504, 5,1},
		{"B¶o r­¬ng tinh s­¬ng kh«i", 4505, 6,2},
		{"B¶o r­¬ng tinh s­¬ng th­îng giíi", 4506, 7,3},	
		{"B¶o r­¬ng tinh s­¬ng hé uyÓn", 4507, 8,4},
		{"B¶o r­¬ng tinh s­¬ng yªu ®¸i",4508, 9,5},
		{"B¶o r­¬ng tinh s­¬ng kh¶i",4509, 0,6},
		{"B¶o r­¬ng tinh s­¬ng vò khİ",4510, 1,7},
		{"B¶o r­¬ng tinh s­¬ng hµi",4511, 2,8},
		{"B¶o r­¬ng tinh s­¬ng ngäc béi",4512, 3,9},
		{"B¶o r­¬ng tinh s­¬ng h¹ giíi",4513, 4,10}	
},


}

roll_cfg_ts_max =  {
	[1] = {
{"Tinh S­¬ng Khæ §Õ Ch©u Liªn",6481},
{"Tinh S­¬ng Khæ §Õ T¨ng M¹o",6482},
{"Tinh S­¬ng Khæ §Õ Kim ThiÒn ChØ Hoµn",6483},
{"Tinh S­¬ng Khæ §Õ Hé UyÓn",6484},
{"Tinh S­¬ng Khæ §Õ Yªu §¸i",6485},
{"Tinh S­¬ng Khæ §Õ Cµ Sa",6486},
{"Tinh S­¬ng Khæ §Õ TriÒn Thñ",6487},
{"Tinh S­¬ng Khæ §Õ T¨ng Hµi",6488},
{"Tinh S­¬ng Khæ §Õ Yªu Trôy",6489},
{"Tinh S­¬ng Khæ §Õ HuyÒn Trang ChØ Hoµn",6490},
{"Tinh S­¬ng DiÖt §Õ PhËt Ch©u",6491},
{"Tinh S­¬ng DiÖt §Õ T¨ng M¹o",6492},
{"Tinh S­¬ng DiÖt §Õ §¹i Tõ ChØ Hoµn",6493},
{"Tinh S­¬ng DiÖt §Õ Hé UyÓn",6494},
{"Tinh S­¬ng DiÖt §Õ Yªu §¸i",6495},
{"Tinh S­¬ng DiÖt §Õ Cµ Sa",6496},
{"Tinh S­¬ng DiÖt §Õ Ph¸p C«n",6497},
{"Tinh S­¬ng DiÖt §Õ T¨ng Hµi",6498},
{"Tinh S­¬ng DiÖt §Õ Yªu Trôy",6499},
{"Tinh S­¬ng DiÖt §Õ §¹i Bi ChØ Hoµn",6500},
{"Tinh S­¬ng §¹o §Õ H¹ng Liªn",6501},
{"Tinh S­¬ng §¹o §Õ T¨ng M¹o",6502},
{"Tinh S­¬ng §¹o §Õ §¹i Thõa ChØ Hoµn",6503},
{"Tinh S­¬ng §¹o §Õ Hé UyÓn",6504},
{"Tinh S­¬ng §¹o §Õ Yªu §¸i",6505},
{"Tinh S­¬ng §¹o §Õ Cµ Sa",6506},
{"Tinh S­¬ng §¹o §Õ Giíi §ao",6507},
{"Tinh S­¬ng §¹o §Õ T¨ng Hµi",6508},
{"Tinh S­¬ng §¹o §Õ Yªu Trôy",6509},
{"Tinh S­¬ng §¹o §Õ TiÓu Thõa ChØ Hoµn",6510},
{"Tinh S­¬ng Th«n Tµ H¹ng Liªn",6511},
{"Tinh S­¬ng Th«n Tµ Kh«i",6512},
{"Tinh S­¬ng Th«n Tµ Nh­ ı ChØ Hoµn",6513},
{"Tinh S­¬ng Th«n Tµ Thóc UyÓn",6514},
{"Tinh S­¬ng Th«n Tµ Yªu §¸i",6515},
{"Tinh S­¬ng Th«n Tµ Kh¶i",6516},
{"Tinh S­¬ng Th«n Tµ ThÇn Chïy",6517},
{"Tinh S­¬ng Th«n Tµ Ngoa",6518},
{"Tinh S­¬ng Th«n Tµ Qu¶i Trôy",6519},
{"Tinh S­¬ng Th«n Tµ TŞch Tµ ChØ Hoµn",6520},
{"Tinh S­¬ng L­u Kim H¹ng Liªn",6521},
{"Tinh S­¬ng L­u Kim Kh«i",6522},
{"Tinh S­¬ng L­u Kim §µn H­¬ng ChØ Hoµn",6523},
{"Tinh S­¬ng L­u Kim Thóc UyÓn",6524},
{"Tinh S­¬ng L­u Kim Yªu §¸i",6525},
{"Tinh S­¬ng L­u Kim Kh¶i",6526},
{"Tinh S­¬ng L­u Kim Th­¬ng",6527},
{"Tinh S­¬ng L­u Kim Ngoa",6528},
{"Tinh S­¬ng L­u Kim Yªu Trôy",6529},
{"Tinh S­¬ng L­u Kim TrÇm H­¬ng ChØ Hoµn",6530},
{"Tinh S­¬ng L÷ S­¬ng H¹ng Liªn",6531},
{"Tinh S­¬ng L÷ S­¬ng Kh«i",6532},
{"Tinh S­¬ng L÷ S­¬ng Long §¶m ChØ Hoµn",6533},
{"Tinh S­¬ng L÷ S­¬ng Thóc UyÓn",6534},
{"Tinh S­¬ng L÷ S­¬ng Yªu §¸i",6535},
{"Tinh S­¬ng L÷ S­¬ng Kh¶i",6536},
{"Tinh S­¬ng L÷ S­¬ng B¶o §ao",6537},
{"Tinh S­¬ng L÷ S­¬ng Ngoa",6538},
{"Tinh S­¬ng L÷ S­¬ng Yªu Trôy",6539},
{"Tinh S­¬ng L÷ S­¬ng Ph­îng T×nh ChØ Hoµn",6540},
{"Tinh S­¬ng L¹c Anh Ch©u Liªn",6541},
{"Tinh S­¬ng L¹c Anh Ph¸t §¸i",6542},
{"Tinh S­¬ng L¹c Anh Minh Ch©u ChØ Hoµn",6543},
{"Tinh S­¬ng L¹c Anh L­u V©n Tô",6544},
{"Tinh S­¬ng L¹c Anh Ti §¸i",6545},
{"Tinh S­¬ng L¹c Anh Nghª Th­êng Vò Y",6546},
{"Tinh S­¬ng L¹c Anh B¶o KiÕm",6547},
{"Tinh S­¬ng L¹c Anh L÷",6548},
{"Tinh S­¬ng L¹c Anh H­¬ng Nang",6549},
{"Tinh S­¬ng L¹c Anh Bİch Ngäc ChØ Hoµn",6550},
{"Tinh S­¬ng PhÊt HuyÖt Ch©u Liªn",6551},
{"Tinh S­¬ng PhÊt HuyÖt Ph¸t §¸i",6552},
{"Tinh S­¬ng PhÊt HuyÖt L­u Li ChØ Hoµn",6553},
{"Tinh S­¬ng PhÊt HuyÖt TuyÕt ¶nh Tô",6554},
{"Tinh S­¬ng PhÊt HuyÖt Ti §¸i",6555},
{"Tinh S­¬ng PhÊt HuyÖt TuyÕt Tiªu Y",6556},
{"Tinh S­¬ng PhÊt HuyÖt TriÒn Thñ",6557},
{"Tinh S­¬ng PhÊt HuyÖt Ngoa",6558},
{"Tinh S­¬ng PhÊt HuyÖt H­¬ng Nang",6559},
{"Tinh S­¬ng PhÊt HuyÖt Thñy Tinh ChØ Hoµn",6560},
{"Tinh S­¬ng Thiªn H­¬ng Ch©u Liªn",6561},
{"Tinh S­¬ng Thiªn H­¬ng Tr©m",6562},
{"Tinh S­¬ng Thiªn H­¬ng TuyÕt Ngäc ChØ Hoµn",6563},
{"Tinh S­¬ng Thiªn H­¬ng CÈm Tó Hé UyÓn",6564},
{"Tinh S­¬ng Thiªn H­¬ng Yªu §¸i",6565},
{"Tinh S­¬ng Thiªn H­¬ng Khëi La Sam",6566},
{"Tinh S­¬ng Thiªn H­¬ng B¶o §ao",6567},
{"Tinh S­¬ng Thiªn H­¬ng Ngoa",6568},
{"Tinh S­¬ng Thiªn H­¬ng H­¬ng Nang",6569},
{"Tinh S­¬ng Thiªn H­¬ng MÆc Ngäc ChØ Hoµn",6570},
{"Tinh S­¬ng Th¸i VËn Ch©u Liªn",6571},
{"Tinh S­¬ng Th¸i VËn Tr©m",6572},
{"Tinh S­¬ng Th¸i VËn Linh Lung ChØ Hoµn",6573},
{"Tinh S­¬ng Th¸i VËn Sinh Hoa Thñ Tr¹c",6574},
{"Tinh S­¬ng Th¸i VËn Ti §¸i",6575},
{"Tinh S­¬ng Th¸i VËn Th¸i §iÖp Y",6576},
{"Tinh S­¬ng Th¸i VËn Uyªn ¦¬ng §ao",6577},
{"Tinh S­¬ng Th¸i VËn Ngoa",6578},
{"Tinh S­¬ng Th¸i VËn H­¬ng Nang",6579},
{"Tinh S­¬ng Th¸i VËn San H« ChØ Hoµn",6580},
{"Tinh S­¬ng ThiÒm Phi H¹ng Liªn",6581},
{"Tinh S­¬ng ThiÒm Phi Ph¸t §¸i",6582},
{"Tinh S­¬ng ThiÒm Phi HuyÕt Tİch ChØ Hoµn",6583},
{"Tinh S­¬ng ThiÒm Phi Hé UyÓn",6584},
{"Tinh S­¬ng ThiÒm Phi Yªu §¸i",6585},
{"Tinh S­¬ng ThiÒm Phi Cæ Y",6586},
{"Tinh S­¬ng ThiÒm Phi TriÒn Thñ",6587},
{"Tinh S­¬ng ThiÒm Phi Ngoa",6588},
{"Tinh S­¬ng ThiÒm Phi Yªu Trôy",6589},
{"Tinh S­¬ng ThiÒm Phi Kh« L©u ChØ Hoµn",6590},
{"Tinh S­¬ng Phô Cèt H¹ng Liªn",6591},
{"Tinh S­¬ng Phô Cèt Ph¸t §¸i",6592},
{"Tinh S­¬ng Phô Cèt HuyÒn ¢m Giíi",6593},
{"Tinh S­¬ng Phô Cèt Hé UyÓn",6594},
{"Tinh S­¬ng Phô Cèt Yªu §¸i",6595},
{"Tinh S­¬ng Phô Cèt Hé Gi¸p",6596},
{"Tinh S­¬ng Phô Cèt HuyÕt NhËn",6597},
{"Tinh S­¬ng Phô Cèt Ngoa",6598},
{"Tinh S­¬ng Phô Cèt Yªu Trôy",6599},
{"Tinh S­¬ng Phô Cèt HuyÒn U Giíi",6600},
{"Tinh S­¬ng L·nh HuyÕt H¹ng Liªn",6601},
{"Tinh S­¬ng L·nh HuyÕt Qu¸n",6602},
{"Tinh S­¬ng L·nh HuyÕt Phi Hoa ChØ Hoµn",6603},
{"Tinh S­¬ng L·nh HuyÕt Hé UyÓn",6604},
{"Tinh S­¬ng L·nh HuyÕt TriÒn Yªu",6605},
{"Tinh S­¬ng L·nh HuyÕt Gi¸p",6606},
{"Tinh S­¬ng L·nh HuyÕt Phi §ao",6607},
{"Tinh S­¬ng L·nh HuyÕt L÷",6608},
{"Tinh S­¬ng L·nh HuyÕt Béi",6609},
{"Tinh S­¬ng L·nh HuyÕt Trİch DiÖp ChØ Hoµn",6610},
{"Tinh S­¬ng Né Liªn H¹ng Liªn",6611},
{"Tinh S­¬ng Né Liªn Qu¸n",6612},
{"Tinh S­¬ng Né Liªn Linh Xµ ChØ Hoµn",6613},
{"Tinh S­¬ng Né Liªn Hé UyÓn",6614},
{"Tinh S­¬ng Né Liªn Thóc Yªu",6615},
{"Tinh S­¬ng Né Liªn Gi¸p Y",6616},
{"Tinh S­¬ng Né Liªn Tô TiÔn",6617},
{"Tinh S­¬ng Né Liªn L÷",6618},
{"Tinh S­¬ng Né Liªn Yªu Trôy",6619},
{"Tinh S­¬ng Né Liªn Kim ThiÒm ChØ Hoµn",6620},
{"Tinh S­¬ng Truy MÖnh H¹ng Liªn",6621},
{"Tinh S­¬ng Truy MÖnh Ph¸t Qu¸n",6622},
{"Tinh S­¬ng Truy MÖnh NhiÕp Ph¸ch ChØ Hoµn",6623},
{"Tinh S­¬ng Truy MÖnh Hé UyÓn",6624},
{"Tinh S­¬ng Truy MÖnh Thóc Yªu",6625},
{"Tinh S­¬ng Truy MÖnh Gi¸p Y",6626},
{"Tinh S­¬ng Truy MÖnh Phi Tiªu",6627},
{"Tinh S­¬ng Truy MÖnh L÷",6628},
{"Tinh S­¬ng Truy MÖnh Yªu Trôy",6629},
{"Tinh S­¬ng Truy MÖnh §o¹t Hån ChØ Hoµn",6630},
{"Tinh S­¬ng M·nh Long H¹ng Liªn",6631},
{"Tinh S­¬ng M·nh Long §Çu Hoµn",6632},
{"Tinh S­¬ng M·nh Long V¹n Tr­îng ChØ Hoµn",6633},
{"Tinh S­¬ng M·nh Long Hé UyÓn",6634},
{"Tinh S­¬ng M·nh Long Thóc Yªu",6635},
{"Tinh S­¬ng M·nh Long C¸i Y",6636},
{"Tinh S­¬ng M·nh Long TriÒn Thñ",6637},
{"Tinh S­¬ng M·nh Long Ngoa",6638},
{"Tinh S­¬ng M·nh Long Yªu Trôy",6639},
{"Tinh S­¬ng M·nh Long Thiªn Lİ ChØ Hoµn",6640},
{"Tinh S­¬ng Ph¸ Lç H¹ng Liªn",6641},
{"Tinh S­¬ng Ph¸ Lç §Çu Hoµn",6642},
{"Tinh S­¬ng Ph¸ Lç Lôc Long Ban ChØ",6643},
{"Tinh S­¬ng Ph¸ Lç Hé UyÓn",6644},
{"Tinh S­¬ng Ph¸ Lç Thóc Yªu",6645},
{"Tinh S­¬ng Ph¸ Lç C¸i Y",6646},
{"Tinh S­¬ng Ph¸ Lç Tr­îng",6647},
{"Tinh S­¬ng Ph¸ Lç Ngoa",6648},
{"Tinh S­¬ng Ph¸ Lç Yªu Trôy",6649},
{"Tinh S­¬ng Ph¸ Lç Linh Th¹ch Ban ChØ",6650},
{"Tinh S­¬ng LuyÖn NhËt H¹ng QuyÓn",6651},
{"Tinh S­¬ng LuyÖn NhËt Kh«i",6652},
{"Tinh S­¬ng LuyÖn NhËt LiÖt DiÔm Ban ChØ",6653},
{"Tinh S­¬ng LuyÖn NhËt Hé UyÓn",6654},
{"Tinh S­¬ng LuyÖn NhËt Yªu §¸i",6655},
{"Tinh S­¬ng LuyÖn NhËt Gi¸p",6656},
{"Tinh S­¬ng LuyÖn NhËt Th­¬ng",6657},
{"Tinh S­¬ng LuyÖn NhËt Ngoa",6658},
{"Tinh S­¬ng LuyÖn NhËt Béi",6659},
{"Tinh S­¬ng LuyÖn NhËt HuyÕt Thó Ban ChØ",6660},
{"Tinh S­¬ng Khèc Viªm H¹ng Liªn",6661},
{"Tinh S­¬ng Khèc Viªm Qu¸n MiÖn",6662},
{"Tinh S­¬ng Khèc Viªm Dung Nham ChØ Hoµn",6663},
{"Tinh S­¬ng Khèc Viªm Hé UyÓn",6664},
{"Tinh S­¬ng Khèc Viªm Yªu §¸i",6665},
{"Tinh S­¬ng Khèc Viªm Gi¸p Y",6666},
{"Tinh S­¬ng Khèc Viªm B¶o §ao",6667},
{"Tinh S­¬ng Khèc Viªm Ngoa",6668},
{"Tinh S­¬ng Khèc Viªm Béi",6669},
{"Tinh S­¬ng Khèc Viªm D­¬ng Viªm ChØ Hoµn",6670},
{"Tinh S­¬ng ChÊn S¬n Phï",6671},
{"Tinh S­¬ng ChÊn S¬n Qu¸n",6672},
{"Tinh S­¬ng ChÊn S¬n VÜnh Sinh ChØ Hoµn",6673},
{"Tinh S­¬ng ChÊn S¬n Tô",6674},
{"Tinh S­¬ng ChÊn S¬n Ph¸p §¸i",6675},
{"Tinh S­¬ng ChÊn S¬n §¹o Bµo",6676},
{"Tinh S­¬ng Ch©n S¬n ThÇn KiÕm",6677},
{"Tinh S­¬ng ChÊn S¬n L÷",6678},
{"Tinh S­¬ng ChÊn S¬n Ngäc Béi",6679},
{"Tinh S­¬ng ChÊn S¬n §¹o Hµnh ChØ Hoµn",6680},
{"Tinh S­¬ng Qu©n Uy Phï",6681},
{"Tinh S­¬ng Qu©n Uy Qu¸n",6682},
{"Tinh S­¬ng Qu©n Uy H»ng Cöu Ph¸p Giíi",6683},
{"Tinh S­¬ng Qu©n Uy Tô",6684},
{"Tinh S­¬ng Qu©n Uy Ph¸p §¸i",6685},
{"Tinh S­¬ng Qu©n Uy §¹o Bµo",6686},
{"Tinh S­¬ng Qu©n Uy ThÇn KiÕm",6687},
{"Tinh S­¬ng Qu©n Uy L÷",6688},
{"Tinh S­¬ng Qu©n Uy Ngäc Béi",6689},
{"Tinh S­¬ng Qu©n Uy BÊt DiÖt Ph¸p Giíi",6690},
{"Tinh S­¬ng Minh L«i H¹ng Liªn",6691},
{"Tinh S­¬ng Minh L«i §¹o Qu¸n",6692},
{"Tinh S­¬ng Minh L«i Träng D­¬ng Giíi",6693},
{"Tinh S­¬ng Minh L«i Hé UyÓn",6694},
{"Tinh S­¬ng Minh L«i Yªu §¸i",6695},
{"Tinh S­¬ng Minh L«i §¹o Bµo",6696},
{"Tinh S­¬ng Minh L«i B¶o §ao",6697},
{"Tinh S­¬ng Minh L«i Ngoa",6698},
{"Tinh S­¬ng Minh L«i Béi",6699},
{"Tinh S­¬ng Minh L«i Cµn Kh«n Giíi",6700},
{"Tinh S­¬ng Oanh Minh Phï",6701},
{"Tinh S­¬ng Oanh Minh §¹o Qu¸n",6702},
{"Tinh S­¬ng Oanh Minh Linh Ngäc ChØ Hoµn",6703},
{"Tinh S­¬ng Oanh Minh Hé UyÓn",6704},
{"Tinh S­¬ng Oanh Minh Yªu §¸i",6705},
{"Tinh S­¬ng Oanh Minh §¹o Bµo",6706},
{"Tinh S­¬ng Oanh Minh ThÇn KiÕm",6707},
{"Tinh S­¬ng Oanh Minh Ngoa",6708},
{"Tinh S­¬ng Oanh Minh Béi",6709},
{"Tinh S­¬ng Oanh Minh D­¬ng Chi ChØ Hoµn",6710},
{"Tinh S­¬ng H¹o Thiªn H¹ng Liªn",6711},
{"Tinh S­¬ng H¹o Thiªn Qu¸n",6712},
{"Tinh S­¬ng H¹o Thiªn Thiªn ThÇn ChØ Hoµn",6713},
{"Tinh S­¬ng H¹o Thiªn Hé UyÓn",6714},
{"Tinh S­¬ng H¹o Thiªn Yªu §¸i",6715},
{"Tinh S­¬ng H¹o Thiªn Y",6716},
{"Tinh S­¬ng H¹o Thiªn KiÕm",6717},
{"Tinh S­¬ng H¹o Thiªn Ngoa",6718},
{"Tinh S­¬ng H¹o Thiªn H­¬ng Nang",6719},
{"Tinh S­¬ng H¹o Thiªn Thiªn C¬ ChØ Hoµn",6720},
{"Tinh S­¬ng Thanh H­ H¹ng Liªn",6721},
{"Tinh S­¬ng Thanh H­ Qu¸n",6722},
{"Tinh S­¬ng Thanh H­ §Şa Vi ChØ Hoµn",6723},
{"Tinh S­¬ng Thanh H­ Hé UyÓn",6724},
{"Tinh S­¬ng Thanh H­ Yªu §¸i",6725},
{"Tinh S­¬ng Thanh H­ Y",6726},
{"Tinh S­¬ng Thanh H­ KiÕm",6727},
{"Tinh S­¬ng Thanh H­ Ngoa",6728},
{"Tinh S­¬ng Thanh H­ H­¬ng Nang",6729},
{"Tinh S­¬ng Thanh H­ §Şa Tİch ChØ Hoµn",6730},

},
	
	[2] = {
		{"B¶o r­¬ng tinh s­¬ng h¹ng liªn max", 4588, 1,1},
		{"B¶o r­¬ng tinh s­¬ng kh«i max", 4589, 2,2},
		{"B¶o r­¬ng tinh s­¬ng th­îng giíi max", 4590, 3,3},	
		{"B¶o r­¬ng tinh s­¬ng hé uyÓn max", 4591, 4,4},
		{"B¶o r­¬ng tinh s­¬ng yªu ®¸i max",4592, 5,5},
		{"B¶o r­¬ng tinh s­¬ng kh¶i max",4593, 6,6},
		{"B¶o r­¬ng tinh s­¬ng vò khİ max",4594, 7,7},
		{"B¶o r­¬ng tinh s­¬ng hµi max",4595, 8,8},
		{"B¶o r­¬ng tinh s­¬ng ngäc béi max",4596, 9,9},
		{"B¶o r­¬ng tinh s­¬ng h¹ giíi max",4597,0,10}	
},


}

roll_cfg_nk =  {
	[1] = {

				{"NguyÖt KhuyÕt Träng KiÕp Ch©u Liªn",3655},
				{"NguyÖt KhuyÕt Träng KiÕp T¨ng M·o",3656},
				{"NguyÖt KhuyÕt Träng KiÕp Kim ThiÒn ChØ Hoµn ",3657},
				{"NguyÖt KhuyÕt Träng KiÕp Hé UyÓn",3658},
				{"NguyÖt KhuyÕt Träng KiÕp Yªu §¸i",3659},
				{"NguyÖt KhuyÕt Träng KiÕp Cµ Sa",3660},
				{"NguyÖt KhuyÕt Träng KiÕp TriÒn Thñ",3661},
				{"NguyÖt KhuyÕt Träng KiÕp T¨ng Hµi",3662},
				{"NguyÖt KhuyÕt Träng KiÕp Yªu Trôy",3663},
				{"NguyÖt KhuyÕt Träng KiÕp HuyÒn Trang ChØ Hoµn",3664},
				{"NguyÖt KhuyÕt S¸t KiÕp PhËt Ch©u",3665},
				{"NguyÖt KhuyÕt S¸t KiÕp T¨ng M·o",3666},
				{"NguyÖt KhuyÕt S¸t KiÕp §¹i Tõ ChØ Hoµn",3667},
				{"NguyÖt KhuyÕt S¸t KiÕp Hé UyÓn",3668},
				{"NguyÖt KhuyÕt S¸t KiÕp Yªu §¸i",3669},
				{"NguyÖt KhuyÕt S¸t KiÕp Cµ Sa",3670},
				{"NguyÖt KhuyÕt S¸t KiÕp Ph¸p C«n",3671},
				{"NguyÖt KhuyÕt S¸t KiÕp T¨ng Hµi",3672},
				{"NguyÖt KhuyÕt S¸t KiÕp Yªu Trôy",3673},
				{"NguyÖt KhuyÕt S¸t KiÕp §¹i Bi ChØ Hoµn",3674},
				{"NguyÖt KhuyÕt Ph¸ KiÕp H¹ng Liªn",3675},
				{"NguyÖt KhuyÕt Ph¸ KiÕp T¨ng M·o",3676},
				{"NguyÖt KhuyÕt Ph¸ KiÕp §¹i Thõa ChØ Hoµn",3677},
				{"NguyÖt KhuyÕt Ph¸ KiÕp Hé UyÓn",3678},
				{"NguyÖt KhuyÕt Ph¸ KiÕp Yªu §¸i",3679},
				{"NguyÖt KhuyÕt Ph¸ KiÕp Cµ Sa",3680},
				{"NguyÖt KhuyÕt Ph¸ KiÕp Giíi §ao",3681},
				{"NguyÖt KhuyÕt Ph¸ KiÕp T¨ng Hµi",3682},
				{"NguyÖt KhuyÕt Ph¸ KiÕp Yªu Trôy",3683},
				{"NguyÖt KhuyÕt Ph¸ KiÕp TiÓu Thõa ChØ Hoµn",3684},
				{"NguyÖt KhuyÕt Ph¸ KiÕp H¹ng Liªn",3685},
				{"NguyÖt KhuyÕt PhÊn Vò Kh«i",3686},
				{"NguyÖt KhuyÕt PhÊn Vò Nh­ ı ChØ Hoµn",3687},
				{"NguyÖt KhuyÕt PhÊn Vò Thóc UyÓn",3688},
				{"NguyÖt KhuyÕt PhÊn Vò Yªu §¸i",3689},
				{"NguyÖt KhuyÕt PhÊn Vò Kh¶i",3690},
				{"NguyÖt KhuyÕt PhÊn Vò ThÇn Chïy",3691},
				{"NguyÖt KhuyÕt PhÊn Vò Ngoa",3692},
				{"NguyÖt KhuyÕt PhÊn Vò Qu¶i Trôy",3693},
				{"NguyÖt KhuyÕt PhÊn Vò Tİch Tµ ChØ Hoµn",3694},
				{"NguyÖt KhuyÕt Phong Yªn H¹ng Liªn",3695},
				{"NguyÖt KhuyÕt Phong Yªn Kh«i",3696},
				{"NguyÖt KhuyÕt Phong Yªn §µn Yªn ChØ Hoµn",3697},
				{"NguyÖt KhuyÕt Phong Yªn Thóc UyÓn",3698},
				{"NguyÖt KhuyÕt Phong Yªn Yªu §¸i",3699},
				{"NguyÖt KhuyÕt Phong Yªn  Kh¶i",3700},
				{"NguyÖt KhuyÕt Phong Yªn  Th­¬ng",3701},
				{"NguyÖt KhuyÕt Phong Yªn Ngoa",3702},
				{"NguyÖt KhuyÕt Phong Yªn Yªu Trôy",3703},
				{"NguyÖt KhuyÕt Phong Yªn TrÇm H­¬ng ChØ Hoµn",3704},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng H¹ng Liªn",3705},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Kh«i",3706},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Long §¶m ChØ Hoµn",3707},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Thóc UyÓn",3708},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Yªu §¸i",3709},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Kh¶i",3710},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng B¶o §ao",3711},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Ngoa",3712},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Yªu Trôy",3713},
				{"NguyÖt KhuyÕt Tr­êng Kh«ng Phông T×nh ChØ Hoµn",3714},
				{"NguyÖt KhuyÕt Kinh Hång Ch©u Liªn",3715},
				{"NguyÖt KhuyÕt Kinh Hång Ph¸t §¸i",3716},
				{"NguyÖt KhuyÕt Kinh Hång Minh Ch©u ChØ Hoµn",3717},
				{"NguyÖt KhuyÕt Kinh Hång L­u V©n Tô",3718},
				{"NguyÖt KhuyÕt Kinh Hång Ti §¸i",3719},
				{"NguyÖt KhuyÕt Kinh Hång Nghª Th­êng Vò Y",3720},
				{"NguyÖt KhuyÕt Kinh Hång B¶o KiÕm",3721},
				{"NguyÖt KhuyÕt Kinh Hång Lİ",3722},
				{"NguyÖt KhuyÕt Kinh Hång H­¬ng Nang",3723},
				{"NguyÖt KhuyÕt Kinh Hång Bİch Ngäc ChØ Hoµn",3724},
				{"NguyÖt KhuyÕt HiÓu NguyÖt Ch©u Liªn",3725},
				{"NguyÖt KhuyÕt HiÓu NguyÖt Ph¸t §¸i",3726},
				{"NguyÖt KhuyÕt HiÓu NguyÖt L­u Li ChØ Hoµn",3727},
				{"NguyÖt KhuyÕt HiÓu NguyÖt TuyÕt ¶nh Tô",3728},
				{"NguyÖt KhuyÕt HiÓu NguyÖt Ti §¸i",3729},
				{"NguyÖt KhuyÕt HiÓu NguyÖt TuyÕt Tiªu Y",3730},
				{"NguyÖt KhuyÕt HiÓu NguyÖt TriÒn Thñ",3731},
				{"NguyÖt KhuyÕt HiÓu NguyÖt Ngoa",3732},
				{"NguyÖt KhuyÕt HiÓu NguyÖt H­¬ng Nang",3733},
				{"NguyÖt KhuyÕt HiÓu NguyÖt Thñy Tinh ChØ Hoµn",3734},
				{"NguyÖt KhuyÕt T­¬ng T­ Ch©u Liªn",3735},
				{"NguyÖt KhuyÕt T­¬ng T­ Tr©m",3736},
				{"NguyÖt KhuyÕt T­¬ng T­ TuyÕt Ngäc ChØ Hoµn",3737},
				{"NguyÖt KhuyÕt T­¬ng T­ CÈm Tó Hé UyÓn",3738},
				{"NguyÖt KhuyÕt T­¬ng T­ Yªu §¸i",3739},
				{"NguyÖt KhuyÕt T­¬ng T­ û La Sam",3740},
				{"NguyÖt KhuyÕt T­¬ng T­ B¶o §ao",3741},
				{"NguyÖt KhuyÕt T­¬ng T­ Ngoa",3742},
				{"NguyÖt KhuyÕt T­¬ng T­ H­¬ng Nang",3743},
				{"NguyÖt KhuyÕt T­¬ng T­ H¾c Ngäc ChØ Hoµn",3744},
				{"NguyÖt KhuyÕt Phong NguyÖt Ch©u Liªn",3745},
				{"NguyÖt KhuyÕt Phong NguyÖt Tr©m",3746},
				{"NguyÖt KhuyÕt Phong NguyÖt Lung Linh  ChØ Hoµn",3747},
				{"NguyÖt KhuyÕt Phong NguyÖt Hoa Sinh Thñ Tr¹c",3748},
				{"NguyÖt KhuyÕt Phong NguyÖt Ti §¸i",3749},
				{"NguyÖt KhuyÕt Phong NguyÖt Th¸i §iÖp Y",3750},
				{"NguyÖt KhuyÕt Phong NguyÖt Uyªn ¦¬ng §ao",3751},
				{"NguyÖt KhuyÕt Phong NguyÖt Ngoa",3752},
				{"NguyÖt KhuyÕt Phong NguyÖt H­¬ng Nang",3753},
				{"NguyÖt KhuyÕt Phong NguyÖt San Hå ChØ Hoµn",3754},
				{"NguyÖt KhuyÕt B¸ch §éc H¹ng Liªn",3755},
				{"NguyÖt KhuyÕt B¸ch §éc Ph¸t §¸i",3756},
				{"NguyÖt KhuyÕt B¸ch §éc HuyÕt Tİch ChØ Hoµn",3757},
				{"NguyÖt KhuyÕt B¸ch §éc Hé UyÓn",3758},
				{"NguyÖt KhuyÕt B¸ch §éc Yªu §¸i",3759},
				{"NguyÖt KhuyÕt B¸ch §éc Cæ Y",3760},
				{"NguyÖt KhuyÕt B¸ch §éc TriÒn Thñ",3761},
				{"NguyÖt KhuyÕt B¸ch §éc Ngoa",3762},
				{"NguyÖt KhuyÕt B¸ch §éc Yªu Trôy",3763},
				{"NguyÖt KhuyÕt B¸ch §éc Kh« L©u ChØ Hoµn",3764},
				{"NguyÖt KhuyÕt U Minh H¹ng Liªn",3765},
				{"NguyÖt KhuyÕt U Minh Ph¸t §¸i",3766},
				{"NguyÖt KhuyÕt U Minh HuyÒn Minh Giíi",3767},
				{"NguyÖt KhuyÕt U Minh Hé UyÓn",3768},
				{"NguyÖt KhuyÕt U Minh Yªu §¸i",3769},
				{"NguyÖt KhuyÕt U Minh Hé Gi¸p",3770},
				{"NguyÖt KhuyÕt U Minh HuyÕt NhÉn",3771},
				{"NguyÖt KhuyÕt U Minh Ngoa",3772},
				{"NguyÖt KhuyÕt U Minh Yªu Trôy",3773},
				{"NguyÖt KhuyÕt U Minh U Minh Giíi",3774},
				{"NguyÖt KhuyÕt Th«i MÖnh H¹ng Liªn",3775},
				{"NguyÖt KhuyÕt Th«i MÖnh Qu¸n",3776},
				{"NguyÖt KhuyÕt Th«i MÖnh Phi Hoa ChØ Hoµn",3777},
				{"NguyÖt KhuyÕt Th«i MÖnh Hé UyÓn",3778},
				{"NguyÖt KhuyÕt Th«i MÖnh TriÒn Yªu",3779},
				{"NguyÖt KhuyÕt Th«i MÖnh Gi¸p",3780},
				{"NguyÖt KhuyÕt Th«i MÖnh Phi §ao",3781},
				{"NguyÖt KhuyÕt Th«i MÖnh Lİ",3782},
				{"NguyÖt KhuyÕt Th«i MÖnh Béi",3783},
				{"NguyÖt KhuyÕt Th«i MÖnh Tİch DiÖp ChØ Hoµn",3784},
				{"NguyÖt KhuyÕt Bİ §éc H¹ng Liªn",3785},
				{"NguyÖt KhuyÕt Bİ §éc Qu¸n",3786},
				{"NguyÖt KhuyÕt Bİ §éc Linh Xµ ChØ Hoµn",3787},
				{"NguyÖt KhuyÕt Bİ §éc Hé UyÓn",3788},
				{"NguyÖt KhuyÕt Bİ §éc Thóc Yªu",3789},
				{"NguyÖt KhuyÕt Bİ §éc Gi¸p Y",3790},
				{"NguyÖt KhuyÕt Bİ §éc Tô TiÔn",3791},
				{"NguyÖt KhuyÕt Bİ §éc Lİ",3792},
				{"NguyÖt KhuyÕt Bİ §éc Yªu Trôy",3793},
				{"NguyÖt KhuyÕt Bİ §éc Kim ThiÒm ChØ Hoµn",3794},
				{"NguyÖt KhuyÕt M¹n §å H¹ng Liªn",3795},
				{"NguyÖt KhuyÕt M¹n §å Ph¸t Qu¸n",3796},
				{"NguyÖt KhuyÕt M¹n §å NhiÕp Ph¸ch ChØ Hoµn",3797},
				{"NguyÖt KhuyÕt M¹n §å Hé UyÓn",3798},
				{"NguyÖt KhuyÕt M¹n §å Thóc Yªu",3799},
				{"NguyÖt KhuyÕt M¹n §å Gi¸p Y",3800},
				{"NguyÖt KhuyÕt M¹n §å Phi Tiªu",3801},
				{"NguyÖt KhuyÕt M¹n §å Lİ",3802},
				{"NguyÖt KhuyÕt M¹n §å Yªu Trôy",3803},
				{"NguyÖt KhuyÕt M¹n §å §o¹t Hån ChØ Hoµn",3804},
				{"NguyÖt KhuyÕt Xİch Long H¹ng Liªn",3805},
				{"NguyÖt KhuyÕt Xİch Long §Çu Hoµn",3806},
				{"NguyÖt KhuyÕt Xİch Long V¹n Ch­ëng ChØ Hoµn",3807},
				{"NguyÖt KhuyÕt Xİch Long Hé UyÓn",3808},
				{"NguyÖt KhuyÕt Xİch Long Thóc Yªu",3809},
				{"NguyÖt KhuyÕt Xİch Long C¸i Y",3810},
				{"NguyÖt KhuyÕt Xİch Long TriÒn Thñ",3811},
				{"NguyÖt KhuyÕt Xİch Long Ngoa",3812},
				{"NguyÖt KhuyÕt Xİch Long Yªu Trôy",3813},
				{"NguyÖt KhuyÕt Xİch Long Thiªn Lı ChØ Hoµn",3814},
				{"NguyÖt KhuyÕt Hµo KiÖt H¹ng Liªn",3815},
				{"NguyÖt KhuyÕt Hµo KiÖt §Çu Hoµn",3816},
				{"NguyÖt KhuyÕt Hµo KiÖt Lôc Long Ph¶n ChØ",3817},
				{"NguyÖt KhuyÕt Hµo KiÖt Hé UyÓn",3818},
				{"NguyÖt KhuyÕt Hµo KiÖt Thóc Yªu",3819},
				{"NguyÖt KhuyÕt Hµo KiÖt C¸i Y",3820},
				{"NguyÖt KhuyÕt Hµo KiÖt Tr­îng",3821},
				{"NguyÖt KhuyÕt Hµo KiÖt Ngoa",3822},
				{"NguyÖt KhuyÕt Hµo KiÖt Yªu Trôy",3823},
				{"NguyÖt KhuyÕt Hµo KiÖt Linh Th¹ch Ph¶n ChØ",3824},
				{"NguyÖt KhuyÕt Tham Lang H¹ng QuyÓn",3825},
				{"NguyÖt KhuyÕt Tham Lang Kh«i",3826},
				{"NguyÖt KhuyÕt Tham Lang LiÖt DiÔm Ph¶n ChØ",3827},
				{"NguyÖt KhuyÕt Tham Lang Hé UyÓn",3828},
				{"NguyÖt KhuyÕt Tham Lang Yªu §¸i",3829},
				{"NguyÖt KhuyÕt Tham Lang Gi¸p",3830},
				{"NguyÖt KhuyÕt Tham Lang Th­¬ng",3831},
				{"NguyÖt KhuyÕt Tham Lang Ngoa",3832},
				{"NguyÖt KhuyÕt Tham Lang Béi",3833},
				{"NguyÖt KhuyÕt Tham Lang HuyÕt Thó Ph¶n ChØ",3834},
				{"NguyÖt KhuyÕt LiÖt D­¬ng H¹ng Liªn",3835},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Qu¸n MiÖn",3836},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Dung Nham ChØ Hoµn",3837},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Hé UyÓn",3838},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Yªu §¸i",3839},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Gi¸p Y",3840},
				{"NguyÖt KhuyÕt LiÖt D­¬ng B¶o §ao",3841},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Ngoa",3842},
				{"NguyÖt KhuyÕt LiÖt D­¬ng Béi",3843},
				{"NguyÖt KhuyÕt LiÖt D­¬ng D­¬ng Viªm ChØ Hoµn",3844},
				{"NguyÖt KhuyÕt Linh §éng Phï",3845},
				{"NguyÖt KhuyÕt Linh §éng Qu¸n",3846},
				{"NguyÖt KhuyÕt Linh §éng VÜnh Sinh ChØ Hoµn",3847},
				{"NguyÖt KhuyÕt Linh §éng Tô",3848},
				{"NguyÖt KhuyÕt Linh §éng Ph¸t §¸i",3849},
				{"NguyÖt KhuyÕt Linh §éng §¹o Bµo",3850},
				{"NguyÖt KhuyÕt Linh §éng ThÇn KiÕm",3851},
				{"NguyÖt KhuyÕt Linh §éng Lİ",3852},
				{"NguyÖt KhuyÕt Linh §éng Ngäc Béi",3853},
				{"NguyÖt KhuyÕt Linh §éng §¹o Hµnh ChØ Hoµn",3854},
				{"NguyÖt KhuyÕt ¶o ¶nh Phï",3855},
				{"NguyÖt KhuyÕt ¶o ¶nh Qu¸n",3856},
				{"NguyÖt KhuyÕt ¶o ¶nh H»ng Cöu Ph¸p Giíi",3857},
				{"NguyÖt KhuyÕt ¶o ¶nh Tô",3858},
				{"NguyÖt KhuyÕt ¶o ¶nh Ph¸t §¸i",3859},
				{"NguyÖt KhuyÕt ¶o ¶nh §¹o Bµo",3860},
				{"NguyÖt KhuyÕt ¶o ¶nh ThÇn KiÕm",3861},
				{"NguyÖt KhuyÕt ¶o ¶nh Lİ",3862},
				{"NguyÖt KhuyÕt ¶o ¶nh Ngäc Béi",3863},
				{"NguyÖt KhuyÕt ¶o ¶nh BÊt DiÖt Ph¸p Giíi",3864},
				{"NguyÖt KhuyÕt L¨ng Phong H¹ng Liªn",3865},
				{"NguyÖt KhuyÕt L¨ng Phong §¹o Qu¸n",3866},
				{"NguyÖt KhuyÕt L¨ng Phong Trïng D­¬ng Giíi",3867},
				{"NguyÖt KhuyÕt L¨ng Phong Hé UyÓn",3868},
				{"NguyÖt KhuyÕt L¨ng Phong Yªu §¸i",3869},
				{"NguyÖt KhuyÕt L¨ng Phong §¹o Bµo",3870},
				{"NguyÖt KhuyÕt L¨ng Phong B¶o §ao",3871},
				{"NguyÖt KhuyÕt L¨ng Phong Ngoa",3872},
				{"NguyÖt KhuyÕt L¨ng Phong Béi",3873},
				{"NguyÖt KhuyÕt L¨ng Phong Cµn Kh«n Giíi",3874},
				{"NguyÖt KhuyÕt Méc Vò Phï",3875},
				{"NguyÖt KhuyÕt Méc Vò §¹o Qu¸n",3876},
				{"NguyÖt KhuyÕt Méc Vò Linh Ngäc ChØ Hoµn",3877},
				{"NguyÖt KhuyÕt Méc Vò Hé UyÓn",3878},
				{"NguyÖt KhuyÕt Méc Vò Yªu §¸i",3879},
				{"NguyÖt KhuyÕt Méc Vò §¹o Bµo",3880},
				{"NguyÖt KhuyÕt Méc Vò ThÇn KiÕm",3881},
				{"NguyÖt KhuyÕt Méc Vò Ngoa",3882},
				{"NguyÖt KhuyÕt Méc Vò Béi",3883},
				{"NguyÖt KhuyÕt Méc Vò D­¬ng Chi ChØ Hoµn",3884},
				{"NguyÖt KhuyÕt DËt ¶nh H¹ng Liªn",3885},
				{"NguyÖt KhuyÕt DËt ¶nh Qu¸n",3886},
				{"NguyÖt KhuyÕt DËt ¶nh Thiªn ThÇn ChØ Hoµn",3887},
				{"NguyÖt KhuyÕt DËt ¶nh Hé UyÓn",3888},
				{"NguyÖt KhuyÕt DËt ¶nh Yªu §¸i",3889},
				{"NguyÖt KhuyÕt DËt ¶nh Y",3890},
				{"NguyÖt KhuyÕt DËt ¶nh KiÕm",3891},
				{"NguyÖt KhuyÕt DËt ¶nh Ngoa",3892},
				{"NguyÖt KhuyÕt DËt ¶nh H­¬ng Nang",3893},
				{"NguyÖt KhuyÕt DËt ¶nh Thiªn C¬ ChØ Hoµn",3894},
				{"NguyÖt KhuyÕt Thanh Phong H¹ng Liªn",3895},
				{"NguyÖt KhuyÕt Thanh Phong Qu¸n",3896},
				{"NguyÖt KhuyÕt Thanh Phong §Şa Vi ChØ Hoµn",3897},
				{"NguyÖt KhuyÕt Thanh Phong Hé UyÓn",3898},
				{"NguyÖt KhuyÕt Thanh Phong Yªu §¸i",3899},
				{"NguyÖt KhuyÕt Thanh Phong Y",3900},
				{"NguyÖt KhuyÕt Thanh Phong KiÕm",3901},
				{"NguyÖt KhuyÕt Thanh Phong Ngoa",3902},
				{"NguyÖt KhuyÕt Thanh Phong H­¬ng Nang",3903},
				{"NguyÖt KhuyÕt Thanh Phong §Şa Tİch ChØ Hoµn",3904},

},
	
	[2] = {
				{"B¶o R­¬ng NguyÖt KhuyÕt H¹ng Liªn",4516,5,1},
				{"B¶o R­¬ng NguyÖt KhuyÕt Kh«i",4517,6,2},
				{"B¶o R­¬ng NguyÖt KhuyÕt Th­îng Giíi",4518,7,3},
				{"B¶o R­¬ng NguyÖt KhuyÕt Hé UyÓn",4519,8,4},
				{"B¶o R­¬ng NguyÖt KhuyÕt Yªu §¸i",4520,9,5},
				{"B¶o R­¬ng NguyÖt KhuyÕt Kh¶i",4521,0,6},
				{"B¶o R­¬ng NguyÖt KhuyÕt Vò Khİ",4522,1,7},
				{"B¶o R­¬ng NguyÖt KhuyÕt Hµi",4523,2,8},
				{"B¶o R­¬ng NguyÖt KhuyÕt Béi",4524,3,9},
				{"B¶o R­¬ng NguyÖt KhuyÕt H¹ Giíi",4525,4,10},
},


}

roll_cfg_nk_max =  {
	[1] = {
{"NguyÖt KhuyÕt Träng KiÕp Ch©u Liªn",5650},
{"NguyÖt KhuyÕt Träng KiÕp T¨ng M·o",5651},
{"NguyÖt KhuyÕt Träng KiÕp Kim ThiÒn ChØ Hoµn ",5652},
{"NguyÖt KhuyÕt Träng KiÕp Hé UyÓn",5653},
{"NguyÖt KhuyÕt Träng KiÕp Yªu §¸i",5654},
{"NguyÖt KhuyÕt Träng KiÕp Cµ Sa",5655},
{"NguyÖt KhuyÕt Träng KiÕp TriÒn Thñ",5656},
{"NguyÖt KhuyÕt Träng KiÕp T¨ng Hµi",5657},
{"NguyÖt KhuyÕt Träng KiÕp Yªu Trôy",5658},
{"NguyÖt KhuyÕt Träng KiÕp HuyÒn Trang ChØ Hoµn",5659},
{"NguyÖt KhuyÕt S¸t KiÕp PhËt Ch©u",5660},
{"NguyÖt KhuyÕt S¸t KiÕp T¨ng M·o",5661},
{"NguyÖt KhuyÕt S¸t KiÕp §¹i Tõ ChØ Hoµn",5662},
{"NguyÖt KhuyÕt S¸t KiÕp Hé UyÓn",5663},
{"NguyÖt KhuyÕt S¸t KiÕp Yªu §¸i",5664},
{"NguyÖt KhuyÕt S¸t KiÕp Cµ Sa",5665},
{"NguyÖt KhuyÕt S¸t KiÕp Ph¸p C«n",5666},
{"NguyÖt KhuyÕt S¸t KiÕp T¨ng Hµi",5667},
{"NguyÖt KhuyÕt S¸t KiÕp Yªu Trôy",5668},
{"NguyÖt KhuyÕt S¸t KiÕp §¹i Bi ChØ Hoµn",5669},
{"NguyÖt KhuyÕt Ph¸ KiÕp H¹ng Liªn",5670},
{"NguyÖt KhuyÕt Ph¸ KiÕp T¨ng M·o",5671},
{"NguyÖt KhuyÕt Ph¸ KiÕp §¹i Thõa ChØ Hoµn",5672},
{"NguyÖt KhuyÕt Ph¸ KiÕp Hé UyÓn",5673},
{"NguyÖt KhuyÕt Ph¸ KiÕp Yªu §¸i",5674},
{"NguyÖt KhuyÕt Ph¸ KiÕp Cµ Sa",5675},
{"NguyÖt KhuyÕt Ph¸ KiÕp Giíi §ao",5676},
{"NguyÖt KhuyÕt Ph¸ KiÕp T¨ng Hµi",5677},
{"NguyÖt KhuyÕt Ph¸ KiÕp Yªu Trôy",5678},
{"NguyÖt KhuyÕt Ph¸ KiÕp TiÓu Thõa ChØ Hoµn",5679},
{"NguyÖt KhuyÕt Ph¸ KiÕp H¹ng Liªn",5680},
{"NguyÖt KhuyÕt PhÊn Vò Kh«i",5681},
{"NguyÖt KhuyÕt PhÊn Vò Nh­ ı ChØ Hoµn",5682},
{"NguyÖt KhuyÕt PhÊn Vò Thóc UyÓn",5683},
{"NguyÖt KhuyÕt PhÊn Vò Yªu §¸i",5684},
{"NguyÖt KhuyÕt PhÊn Vò Kh¶i",5685},
{"NguyÖt KhuyÕt PhÊn Vò ThÇn Chïy",5686},
{"NguyÖt KhuyÕt PhÊn Vò Ngoa",5687},
{"NguyÖt KhuyÕt PhÊn Vò Qu¶i Trôy",5688},
{"NguyÖt KhuyÕt PhÊn Vò Tİch Tµ ChØ Hoµn",5689},
{"NguyÖt KhuyÕt Phong Yªn H¹ng Liªn",5690},
{"NguyÖt KhuyÕt Phong Yªn Kh«i",5691},
{"NguyÖt KhuyÕt Phong Yªn §µn Yªn ChØ Hoµn",5692},
{"NguyÖt KhuyÕt Phong Yªn Thóc UyÓn",5693},
{"NguyÖt KhuyÕt Phong Yªn Yªu §¸i",5694},
{"NguyÖt KhuyÕt Phong Yªn  Kh¶i",5695},
{"NguyÖt KhuyÕt Phong Yªn  Th­¬ng",5696},
{"NguyÖt KhuyÕt Phong Yªn Ngoa",5697},
{"NguyÖt KhuyÕt Phong Yªn Yªu Trôy",5698},
{"NguyÖt KhuyÕt Phong Yªn TrÇm H­¬ng ChØ Hoµn",5699},
{"NguyÖt KhuyÕt Tr­êng Kh«ng H¹ng Liªn",5700},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Kh«i",5701},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Long §¶m ChØ Hoµn",5702},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Thóc UyÓn",5703},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Yªu §¸i",5704},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Kh¶i",5705},
{"NguyÖt KhuyÕt Tr­êng Kh«ng B¶o §ao",5706},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Ngoa",5707},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Yªu Trôy",5708},
{"NguyÖt KhuyÕt Tr­êng Kh«ng Phông T×nh ChØ Hoµn",5709},
{"NguyÖt KhuyÕt Kinh Hång Ch©u Liªn",5710},
{"NguyÖt KhuyÕt Kinh Hång Ph¸t §¸i",5711},
{"NguyÖt KhuyÕt Kinh Hång Minh Ch©u ChØ Hoµn",5712},
{"NguyÖt KhuyÕt Kinh Hång L­u V©n Tô",5713},
{"NguyÖt KhuyÕt Kinh Hång Ti §¸i",5714},
{"NguyÖt KhuyÕt Kinh Hång Nghª Th­êng Vò Y",5715},
{"NguyÖt KhuyÕt Kinh Hång B¶o KiÕm",5716},
{"NguyÖt KhuyÕt Kinh Hång Lİ",5717},
{"NguyÖt KhuyÕt Kinh Hång H­¬ng Nang",5718},
{"NguyÖt KhuyÕt Kinh Hång Bİch Ngäc ChØ Hoµn",5719},
{"NguyÖt KhuyÕt HiÓu NguyÖt Ch©u Liªn",5720},
{"NguyÖt KhuyÕt HiÓu NguyÖt Ph¸t §¸i",5721},
{"NguyÖt KhuyÕt HiÓu NguyÖt L­u Li ChØ Hoµn",5722},
{"NguyÖt KhuyÕt HiÓu NguyÖt TuyÕt ¶nh Tô",5723},
{"NguyÖt KhuyÕt HiÓu NguyÖt Ti §¸i",5724},
{"NguyÖt KhuyÕt HiÓu NguyÖt TuyÕt Tiªu Y",5725},
{"NguyÖt KhuyÕt HiÓu NguyÖt TriÒn Thñ",5726},
{"NguyÖt KhuyÕt HiÓu NguyÖt Ngoa",5727},
{"NguyÖt KhuyÕt HiÓu NguyÖt H­¬ng Nang",5728},
{"NguyÖt KhuyÕt HiÓu NguyÖt Thñy Tinh ChØ Hoµn",5729},
{"NguyÖt KhuyÕt T­¬ng T­ Ch©u Liªn",5730},
{"NguyÖt KhuyÕt T­¬ng T­ Tr©m",5731},
{"NguyÖt KhuyÕt T­¬ng T­ TuyÕt Ngäc ChØ Hoµn",5732},
{"NguyÖt KhuyÕt T­¬ng T­ CÈm Tó Hé UyÓn",5733},
{"NguyÖt KhuyÕt T­¬ng T­ Yªu §¸i",5734},
{"NguyÖt KhuyÕt T­¬ng T­ û La Sam",5735},
{"NguyÖt KhuyÕt T­¬ng T­ B¶o §ao",5736},
{"NguyÖt KhuyÕt T­¬ng T­ Ngoa",5737},
{"NguyÖt KhuyÕt T­¬ng T­ H­¬ng Nang",5738},
{"NguyÖt KhuyÕt T­¬ng T­ H¾c Ngäc ChØ Hoµn",5739},
{"NguyÖt KhuyÕt Phong NguyÖt Ch©u Liªn",5740},
{"NguyÖt KhuyÕt Phong NguyÖt Tr©m",5741},
{"NguyÖt KhuyÕt Phong NguyÖt Lung Linh  ChØ Hoµn",5742},
{"NguyÖt KhuyÕt Phong NguyÖt Hoa Sinh Thñ Tr¹c",5743},
{"NguyÖt KhuyÕt Phong NguyÖt Ti §¸i",5744},
{"NguyÖt KhuyÕt Phong NguyÖt Th¸i §iÖp Y",5745},
{"NguyÖt KhuyÕt Phong NguyÖt Uyªn ¦¬ng §ao",5746},
{"NguyÖt KhuyÕt Phong NguyÖt Ngoa",5747},
{"NguyÖt KhuyÕt Phong NguyÖt H­¬ng Nang",5748},
{"NguyÖt KhuyÕt Phong NguyÖt San Hå ChØ Hoµn",5749},
{"NguyÖt KhuyÕt B¸ch §éc H¹ng Liªn",5750},
{"NguyÖt KhuyÕt B¸ch §éc Ph¸t §¸i",5751},
{"NguyÖt KhuyÕt B¸ch §éc HuyÕt Tİch ChØ Hoµn",5752},
{"NguyÖt KhuyÕt B¸ch §éc Hé UyÓn",5753},
{"NguyÖt KhuyÕt B¸ch §éc Yªu §¸i",5754},
{"NguyÖt KhuyÕt B¸ch §éc Cæ Y",5755},
{"NguyÖt KhuyÕt B¸ch §éc TriÒn Thñ",5756},
{"NguyÖt KhuyÕt B¸ch §éc Ngoa",5757},
{"NguyÖt KhuyÕt B¸ch §éc Yªu Trôy",5758},
{"NguyÖt KhuyÕt B¸ch §éc Kh« L©u ChØ Hoµn",5759},
{"NguyÖt KhuyÕt U Minh H¹ng Liªn",5760},
{"NguyÖt KhuyÕt U Minh Ph¸t §¸i",5761},
{"NguyÖt KhuyÕt U Minh HuyÒn Minh Giíi",5762},
{"NguyÖt KhuyÕt U Minh Hé UyÓn",5763},
{"NguyÖt KhuyÕt U Minh Yªu §¸i",5764},
{"NguyÖt KhuyÕt U Minh Hé Gi¸p",5765},
{"NguyÖt KhuyÕt U Minh HuyÕt NhÉn",5766},
{"NguyÖt KhuyÕt U Minh Ngoa",5767},
{"NguyÖt KhuyÕt U Minh Yªu Trôy",5768},
{"NguyÖt KhuyÕt U Minh U Minh Giíi",5769},
{"NguyÖt KhuyÕt Th«i MÖnh H¹ng Liªn",5770},
{"NguyÖt KhuyÕt Th«i MÖnh Qu¸n",5771},
{"NguyÖt KhuyÕt Th«i MÖnh Phi Hoa ChØ Hoµn",5772},
{"NguyÖt KhuyÕt Th«i MÖnh Hé UyÓn",5773},
{"NguyÖt KhuyÕt Th«i MÖnh TriÒn Yªu",5774},
{"NguyÖt KhuyÕt Th«i MÖnh Gi¸p",5775},
{"NguyÖt KhuyÕt Th«i MÖnh Phi §ao",5776},
{"NguyÖt KhuyÕt Th«i MÖnh Lİ",5777},
{"NguyÖt KhuyÕt Th«i MÖnh Béi",5778},
{"NguyÖt KhuyÕt Th«i MÖnh Tİch DiÖp ChØ Hoµn",5779},
{"NguyÖt KhuyÕt Bİ §éc H¹ng Liªn",5780},
{"NguyÖt KhuyÕt Bİ §éc Qu¸n",5781},
{"NguyÖt KhuyÕt Bİ §éc Linh Xµ ChØ Hoµn",5782},
{"NguyÖt KhuyÕt Bİ §éc Hé UyÓn",5783},
{"NguyÖt KhuyÕt Bİ §éc Thóc Yªu",5784},
{"NguyÖt KhuyÕt Bİ §éc Gi¸p Y",5785},
{"NguyÖt KhuyÕt Bİ §éc Tô TiÔn",5786},
{"NguyÖt KhuyÕt Bİ §éc Lİ",5787},
{"NguyÖt KhuyÕt Bİ §éc Yªu Trôy",5788},
{"NguyÖt KhuyÕt Bİ §éc Kim ThiÒm ChØ Hoµn",5789},
{"NguyÖt KhuyÕt M¹n §å H¹ng Liªn",5790},
{"NguyÖt KhuyÕt M¹n §å Ph¸t Qu¸n",5791},
{"NguyÖt KhuyÕt M¹n §å NhiÕp Ph¸ch ChØ Hoµn",5792},
{"NguyÖt KhuyÕt M¹n §å Hé UyÓn",5793},
{"NguyÖt KhuyÕt M¹n §å Thóc Yªu",5794},
{"NguyÖt KhuyÕt M¹n §å Gi¸p Y",5795},
{"NguyÖt KhuyÕt M¹n §å Phi Tiªu",5796},
{"NguyÖt KhuyÕt M¹n §å Lİ",5797},
{"NguyÖt KhuyÕt M¹n §å Yªu Trôy",5798},
{"NguyÖt KhuyÕt M¹n §å §o¹t Hån ChØ Hoµn",5799},
{"NguyÖt KhuyÕt Xİch Long H¹ng Liªn",5800},
{"NguyÖt KhuyÕt Xİch Long §Çu Hoµn",5801},
{"NguyÖt KhuyÕt Xİch Long V¹n Ch­ëng ChØ Hoµn",5802},
{"NguyÖt KhuyÕt Xİch Long Hé UyÓn",5803},
{"NguyÖt KhuyÕt Xİch Long Thóc Yªu",5804},
{"NguyÖt KhuyÕt Xİch Long C¸i Y",5805},
{"NguyÖt KhuyÕt Xİch Long TriÒn Thñ",5806},
{"NguyÖt KhuyÕt Xİch Long Ngoa",5807},
{"NguyÖt KhuyÕt Xİch Long Yªu Trôy",5808},
{"NguyÖt KhuyÕt Xİch Long Thiªn Lı ChØ Hoµn",5809},
{"NguyÖt KhuyÕt Hµo KiÖt H¹ng Liªn",5810},
{"NguyÖt KhuyÕt Hµo KiÖt §Çu Hoµn",5811},
{"NguyÖt KhuyÕt Hµo KiÖt Lôc Long Ph¶n ChØ",5812},
{"NguyÖt KhuyÕt Hµo KiÖt Hé UyÓn",5813},
{"NguyÖt KhuyÕt Hµo KiÖt Thóc Yªu",5814},
{"NguyÖt KhuyÕt Hµo KiÖt C¸i Y",5815},
{"NguyÖt KhuyÕt Hµo KiÖt Tr­îng",5816},
{"NguyÖt KhuyÕt Hµo KiÖt Ngoa",5817},
{"NguyÖt KhuyÕt Hµo KiÖt Yªu Trôy",5818},
{"NguyÖt KhuyÕt Hµo KiÖt Linh Th¹ch Ph¶n ChØ",5819},
{"NguyÖt KhuyÕt Tham Lang H¹ng QuyÓn",5820},
{"NguyÖt KhuyÕt Tham Lang Kh«i",5821},
{"NguyÖt KhuyÕt Tham Lang LiÖt DiÔm Ph¶n ChØ",5822},
{"NguyÖt KhuyÕt Tham Lang Hé UyÓn",5823},
{"NguyÖt KhuyÕt Tham Lang Yªu §¸i",5824},
{"NguyÖt KhuyÕt Tham Lang Gi¸p",5825},
{"NguyÖt KhuyÕt Tham Lang Th­¬ng",5826},
{"NguyÖt KhuyÕt Tham Lang Ngoa",5827},
{"NguyÖt KhuyÕt Tham Lang Béi",5828},
{"NguyÖt KhuyÕt Tham Lang HuyÕt Thó Ph¶n ChØ",5829},
{"NguyÖt KhuyÕt LiÖt D­¬ng H¹ng Liªn",5830},
{"NguyÖt KhuyÕt LiÖt D­¬ng Qu¸n MiÖn",5831},
{"NguyÖt KhuyÕt LiÖt D­¬ng Dung Nham ChØ Hoµn",5832},
{"NguyÖt KhuyÕt LiÖt D­¬ng Hé UyÓn",5833},
{"NguyÖt KhuyÕt LiÖt D­¬ng Yªu §¸i",5834},
{"NguyÖt KhuyÕt LiÖt D­¬ng Gi¸p Y",5835},
{"NguyÖt KhuyÕt LiÖt D­¬ng B¶o §ao",5836},
{"NguyÖt KhuyÕt LiÖt D­¬ng Ngoa",5837},
{"NguyÖt KhuyÕt LiÖt D­¬ng Béi",5838},
{"NguyÖt KhuyÕt LiÖt D­¬ng D­¬ng Viªm ChØ Hoµn",5839},
{"NguyÖt KhuyÕt Linh §éng Phï",5840},
{"NguyÖt KhuyÕt Linh §éng Qu¸n",5841},
{"NguyÖt KhuyÕt Linh §éng VÜnh Sinh ChØ Hoµn",5842},
{"NguyÖt KhuyÕt Linh §éng Tô",5843},
{"NguyÖt KhuyÕt Linh §éng Ph¸t §¸i",5844},
{"NguyÖt KhuyÕt Linh §éng §¹o Bµo",5845},
{"NguyÖt KhuyÕt Linh §éng ThÇn KiÕm",5846},
{"NguyÖt KhuyÕt Linh §éng Lİ",5847},
{"NguyÖt KhuyÕt Linh §éng Ngäc Béi",5848},
{"NguyÖt KhuyÕt Linh §éng §¹o Hµnh ChØ Hoµn",5849},
{"NguyÖt KhuyÕt ¶o ¶nh Phï",5850},
{"NguyÖt KhuyÕt ¶o ¶nh Qu¸n",5851},
{"NguyÖt KhuyÕt ¶o ¶nh H»ng Cöu Ph¸p Giíi",5852},
{"NguyÖt KhuyÕt ¶o ¶nh Tô",5853},
{"NguyÖt KhuyÕt ¶o ¶nh Ph¸t §¸i",5854},
{"NguyÖt KhuyÕt ¶o ¶nh §¹o Bµo",5855},
{"NguyÖt KhuyÕt ¶o ¶nh ThÇn KiÕm",5856},
{"NguyÖt KhuyÕt ¶o ¶nh Lİ",5857},
{"NguyÖt KhuyÕt ¶o ¶nh Ngäc Béi",5858},
{"NguyÖt KhuyÕt ¶o ¶nh BÊt DiÖt Ph¸p Giíi",5859},
{"NguyÖt KhuyÕt L¨ng Phong H¹ng Liªn",5860},
{"NguyÖt KhuyÕt L¨ng Phong §¹o Qu¸n",5861},
{"NguyÖt KhuyÕt L¨ng Phong Trïng D­¬ng Giíi",5862},
{"NguyÖt KhuyÕt L¨ng Phong Hé UyÓn",5863},
{"NguyÖt KhuyÕt L¨ng Phong Yªu §¸i",5864},
{"NguyÖt KhuyÕt L¨ng Phong §¹o Bµo",5865},
{"NguyÖt KhuyÕt L¨ng Phong B¶o §ao",5866},
{"NguyÖt KhuyÕt L¨ng Phong Ngoa",5867},
{"NguyÖt KhuyÕt L¨ng Phong Béi",5868},
{"NguyÖt KhuyÕt L¨ng Phong Cµn Kh«n Giíi",5869},
{"NguyÖt KhuyÕt Méc Vò Phï",5870},
{"NguyÖt KhuyÕt Méc Vò §¹o Qu¸n",5871},
{"NguyÖt KhuyÕt Méc Vò Linh Ngäc ChØ Hoµn",5872},
{"NguyÖt KhuyÕt Méc Vò Hé UyÓn",5873},
{"NguyÖt KhuyÕt Méc Vò Yªu §¸i",5874},
{"NguyÖt KhuyÕt Méc Vò §¹o Bµo",5875},
{"NguyÖt KhuyÕt Méc Vò ThÇn KiÕm",5876},
{"NguyÖt KhuyÕt Méc Vò Ngoa",5877},
{"NguyÖt KhuyÕt Méc Vò Béi",5878},
{"NguyÖt KhuyÕt Méc Vò D­¬ng Chi ChØ Hoµn",5879},
{"NguyÖt KhuyÕt DËt ¶nh H¹ng Liªn",5880},
{"NguyÖt KhuyÕt DËt ¶nh Qu¸n",5881},
{"NguyÖt KhuyÕt DËt ¶nh Thiªn ThÇn ChØ Hoµn",5882},
{"NguyÖt KhuyÕt DËt ¶nh Hé UyÓn",5883},
{"NguyÖt KhuyÕt DËt ¶nh Yªu §¸i",5884},
{"NguyÖt KhuyÕt DËt ¶nh Y",5885},
{"NguyÖt KhuyÕt DËt ¶nh KiÕm",5886},
{"NguyÖt KhuyÕt DËt ¶nh Ngoa",5887},
{"NguyÖt KhuyÕt DËt ¶nh H­¬ng Nang",5888},
{"NguyÖt KhuyÕt DËt ¶nh Thiªn C¬ ChØ Hoµn",5889},
{"NguyÖt KhuyÕt Thanh Phong H¹ng Liªn",5890},
{"NguyÖt KhuyÕt Thanh Phong Qu¸n",5891},
{"NguyÖt KhuyÕt Thanh Phong §Şa Vi ChØ Hoµn",5892},
{"NguyÖt KhuyÕt Thanh Phong Hé UyÓn",5893},
{"NguyÖt KhuyÕt Thanh Phong Yªu §¸i",5894},
{"NguyÖt KhuyÕt Thanh Phong Y",5895},
{"NguyÖt KhuyÕt Thanh Phong KiÕm",5896},
{"NguyÖt KhuyÕt Thanh Phong Ngoa",5897},
{"NguyÖt KhuyÕt Thanh Phong H­¬ng Nang",5898},
{"NguyÖt KhuyÕt Thanh Phong §Şa Tİch ChØ Hoµn",5899},

},
	
	[2] = {
				{"B¶o R­¬ng NguyÖt KhuyÕt H¹ng Liªn Maxofftion",4600,0,1},
				{"B¶o R­¬ng NguyÖt KhuyÕt Kh«i Maxofftion",4601,1,2},
				{"B¶o R­¬ng NguyÖt KhuyÕt Th­îng Giíi Maxofftion",4602,2,3},
				{"B¶o R­¬ng NguyÖt KhuyÕt Hé UyÓn Maxofftion",4603,3,4},
				{"B¶o R­¬ng NguyÖt KhuyÕt Yªu §¸i Maxofftion",4604,4,5},
				{"B¶o R­¬ng NguyÖt KhuyÕt Kh¶i Maxofftion",4605,5,6},
				{"B¶o R­¬ng NguyÖt KhuyÕt Vò Khİ Maxofftion",4606,6,7},
				{"B¶o R­¬ng NguyÖt KhuyÕt Hµi Maxofftion",4607,7,8},
				{"B¶o R­¬ng NguyÖt KhuyÕt Béi Maxofftion",4608,8,9},
				{"B¶o R­¬ng NguyÖt KhuyÕt H¹ Giíi Maxofftion",4609,9,10},
},


}