-- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com - 
-- script viet hoa By http://tranhba.com  FileName : task_shenzhaoyuan1.lua 
-- script viet hoa By http://tranhba.com  Author : xiaoyang 
-- script viet hoa By http://tranhba.com  CreateTime : 2005-08-31 18:02:14 
-- script viet hoa By http://tranhba.com  Desc : trÇm chiªu xa tay cña c¶o mét lo¹n khëi ph­¬ng t©y 
-- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com -- script viet hoa By http://tranhba.com - 

DescLink_ShenZhaoYuan ="<#><link=image:\\spr\\item\\questkey\\taskobj075.spr> trÇm chiªu xa tay cña c¶o <link>" 

function main() 
Describe(DescLink_ShenZhaoYuan.."<#># thiÖu h­ng ba m­¬i n¨m , hµm chiÕn ®· l©u Trung Nguyªn tèng n­íc cïng b¾c ph­¬ng kim quèc gi÷a tiÕn vµo t­¬ng ®èi b×nh tÜnh mét n¨m . song ph­¬ng ng­ng chiÕn h­u binh , trõ biªn c¶nh th­îng thØnh tho¶ng ph¸t sinh lÎ tÎ xung ®ét , ®¹i thêi ®¹i ®İch giã löa tùa hå t¹m thêi dËp t¾t . Trung Nguyªn ®Şa khu d©n chóng ph¶i lÊy nghØ ng¬i sanh tøc , vèn lµ tr¨m dÆm bªn trong niÓu kh«ng cã ng­êi ë ®İch th«n trang chÕt trÊn l¹i ®æi thµnh míi søc sèng . n¨m nµy mïa hÌ , ®¹o tuÖ th­îng treo ®Çy lÊm tÊm ®İch lé thñy . <enter>" 
.." vËy mµ mét n¨m nµy th¶ vµo toµn bé lŞch sö tr­êng hµ trung còng tÊt ®óng lµ kinh t©m ®éng ph¸ch , mµ l¹i trë vÒ chç l©u d¸ng dÊp mét n¨m . v« cïng t©y ®İch trªn ®¹i th¶o nguyªn , M«ng Cæ trong tói x¸ch truyÒn ®Õn bän trÎ nİt non nít ®İch khãc . bän hä l­u ngay c¶ víi mÉu th©n b·o hßa ®İch söa , cho thÊy v­ît qua tiÒn bèi ®İch thŞnh v­îng sinh mÖnh lùc . nh÷ng ng­êi lín ®Òu nãi , nh÷ng hµi tö nµy t­¬ng lai nhÊt ®Şnh sÏ trë thµnh khÊt nhan bé ®İch ba ®Æc ng­¬i . bän hä ®Òu kh«ng tõng muèn ®Õn , ë ngao ngao ®îi bé ®İch trÎ nİt trung gian , cã mét ng­êi kh«ng chØ cã trë thµnh M«ng Cæ bé téc ®İch anh hïng , thËm chİ thèng lÜnh trø h¾n ®iªu cung thiÕt kş quĞt ngang ©u ¸ ®¹i lôc , hoµn thµnh kho¸ng cæ th­íc kim ®İch nghiÖp b¸ . tªn cña h¾n , gäi thiÕt méc thËt . <enter>" 
.." ¸nh mÆt trêi s¸i m·n tõ b¾c tíi nam mªnh m«ng ®İch hoa h¹ lÜnh vùc , l¹i ®éc ®éc chiÕu kh«ng tíi t©y b¾c biªn thïy bÇn tİch ®İch h¹ n­íc . c¸i nµy tõ ®«n hoµng thµnh ®İch b·o c¸t trung ®i ra ®İch quèc gia , tao ngé tr¨m n¨m khã gÆp ®İch n¹n h¹n h¸n . ngåi ë v­¬ng ®×nh trªn , t©y h¹ quèc chñ nh©n hiÕu ¨n ngñ kh«ng yªn . nh÷ng n¨m gÇn ®©y h¾n ®èi ngo¹i ngay c¶ tèng thÇn kim , èng tay ¸o nghiÔm vò , ®èi víi bªn trong lÖ tinh ®å tr× , khai mét ®êi phong khİ , khiÕn cho t©y h¹ n­íc nghiÔm cã thiÓm cam toµn c¶nh , xóc gi¸c thËm chİ dß vµo M«ng Cæ c¶nh néi . vËy mµ , nh÷ng thø kia phiÕu h·n ®İch du môc d©n téc ®êi sau , ®ang lÊy mét lo¹i thiÕt huyÕt cïng v« t×nh ®İch t¸c phong x©y dùng l¹i trø ®¹i th¶o nguyªn ®İch trËt tù , ®¹i ®éng lo¹n ®İch thêi ®¹i cuèi cïng ®em qu¸ khø , mét thèng nhÊt mµ c­êng thÕ ®İch phong kiÕn quèc gia ®em quËt khëi . rÊt cã chİnh trŞ tr­íc chiªm tİnh ®İch nh©n hiÕu tiªn ®o¸n ®­îc ®iÓm nµy , ®iÒu nµy lµm cho h¾n rÇu rØ kh«ng chŞu næi . ®· bŞ gi¸o hãa ®İch t©y h¹ c¸c con d©n kh«ng ®ë ®­îc kim quèc m¹nh binh , còng kh«ng ®ë ®­îc M«ng Cæ thiÕt kş , nh©n hiÕu tùa hå thÊy ®­îc ®¹i h¹ diÖt vong h«m ®ã ngËp trêi ®¹i háa : háa ho¹n . con chim r¬i vµo v­¬ng ®×nh bªn ngoµi hi hİ , mét chót còng kh«ng c¶m gi¸c ®­îc v¾ng l¹nh ®İch ngù ®iÖn ®ang bŞ ©m Õ bao phñ , t©y H¹ v­¬ng nh©n hiÕu phón löa ®İch hai m¾t tõ tõ ¶m ®¹m xuèng , h¾n triÖu nhËp ng­êi hÇu , lÊy s¸u tr¨m dÆm thªm cÊp kho¸i m· ®­a ®i mét phong th¬ . kia phong tuyÖt bİ ®İch tİn hµm cã thÓ hay kh«ng mang ®Õn kh¸c mét cuéc minh ngôc chi löa ®©y ? tõ tèi nay ®İch trong tinh kh«ng ta ph¶i kh«ng tíi c©u tr¶ lêi . nh­ng lµ , mét n¨m nµy ®İch th¸ng chİn chØ ®Şnh sÏ kh«ng b×nh tÜnh . <enter>" 
.." xem tinh ng­êi trÇm chiªu xa ",1,"KÕt thóc ®èi tho¹i /no") 
return 1 
end 

function no() 
end
